#!/usr/bin/env bash
# EAS Build post-install hook.
#
# Runs on the EAS build VM after `npm install` finishes, before the
# Xcode/Gradle build step. EAS auto-executes this file by convention
# (https://docs.expo.dev/build-reference/npm-hooks/#eas-build-hooks).
#
# Two responsibilities:
#
#   1. Generate ios/sentry.properties from environment variables.
#      The @sentry/react-native build plugin reads this file during
#      `pod install` + Xcode build phases to upload source maps + tag
#      releases. Without it, the build either fails (missing org) or
#      ships unsymbolicated.
#
#   2. Generate android/sentry.properties (same content) for the
#      eventual Android track. Cheap to do now.
#
# Required EAS env vars (set in production environment):
#   - SENTRY_ORG          (e.g. "sparrow-collect")
#   - SENTRY_PROJECT      (e.g. "sparrow-collect")
#   - SENTRY_AUTH_TOKEN   (sentry.io → Account → Auth Tokens, sensitive)
#
# If ANY of those three are unset OR SENTRY_DISABLE_AUTO_UPLOAD=true,
# this script writes a stub properties file with the disable flag so
# the build never fails on missing Sentry config. That means: a fresh
# clone can still build successfully before someone runs
# `scripts/setup_sentry_sourcemap_upload.sh`.

set -euo pipefail

PROPS_IOS="ios/sentry.properties"
PROPS_ANDROID="android/sentry.properties"

mkdir -p "$(dirname "$PROPS_IOS")" "$(dirname "$PROPS_ANDROID")"

if [ "${SENTRY_DISABLE_AUTO_UPLOAD:-}" = "true" ]; then
  echo "[eas-build-post-install] SENTRY_DISABLE_AUTO_UPLOAD=true — writing disable stub"
  cat > "$PROPS_IOS" <<EOF
# Generated by eas-build-post-install.sh.
# Source map upload disabled — see scripts/setup_sentry_sourcemap_upload.sh
# to enable.
defaults.url=https://sentry.io/
EOF
  cp "$PROPS_IOS" "$PROPS_ANDROID"
  exit 0
fi

# Require all three when not disabled. If missing, fall back to disabled
# rather than failing the build — easier to ship a build with no symbols
# than to block on Sentry config.
if [ -z "${SENTRY_ORG:-}" ] || [ -z "${SENTRY_PROJECT:-}" ] || [ -z "${SENTRY_AUTH_TOKEN:-}" ]; then
  echo "[eas-build-post-install] WARNING: SENTRY_ORG/PROJECT/AUTH_TOKEN not all set. Falling back to disable stub."
  echo "  To enable: run scripts/setup_sentry_sourcemap_upload.sh locally and confirm `eas env:list --environment production` shows the three vars."
  cat > "$PROPS_IOS" <<EOF
# Generated by eas-build-post-install.sh — Sentry config incomplete.
defaults.url=https://sentry.io/
EOF
  cp "$PROPS_IOS" "$PROPS_ANDROID"
  exit 0
fi

echo "[eas-build-post-install] Writing $PROPS_IOS + $PROPS_ANDROID with Sentry org=$SENTRY_ORG project=$SENTRY_PROJECT"
cat > "$PROPS_IOS" <<EOF
# Generated by eas-build-post-install.sh — do not commit.
defaults.url=https://sentry.io/
defaults.org=$SENTRY_ORG
defaults.project=$SENTRY_PROJECT
auth.token=$SENTRY_AUTH_TOKEN
EOF
chmod 600 "$PROPS_IOS"
cp "$PROPS_IOS" "$PROPS_ANDROID"
chmod 600 "$PROPS_ANDROID"

echo "[eas-build-post-install] Done. Source maps will upload at build time."
