[mypy]
python_version = 3.11
ignore_missing_imports = True
allow_redefinition = True
warn_unused_ignores = False
disable_error_code = no-untyped-def,no-untyped-call,no-any-return,type-arg,call-arg,return-value,misc
exclude = ^(build|dist|venv|\.venv|tests|app/(ml|training|providers|guide|predict|models|db|infra|middleware))/.*$

[mypy-app.main]
strict = True

[mypy-app.routes.*]
strict_optional = True
