[mypy]
python_version = 3.12
ignore_missing_imports = True
allow_redefinition = True
warn_unused_ignores = False
disable_error_code = no-untyped-def,no-untyped-call,no-any-return,type-arg
exclude = ^(build|dist|venv|\.venv|server/tests|server/app/(ml|training|providers|guide|predict|models|db|infra|middleware))/.*$

[mypy-main]
strict = True

[mypy-app.routes.*]
strict_optional = True

[mypy-app.features.*]
strict_optional = True
