#!/bin/bash
set -e

TARGET="app/build-paint-projects.tsx"

if [ ! -f "$TARGET" ]; then
  echo "❌ ERROR: $TARGET not found"
  exit 1
fi

echo "🔍 Creating backup..."
cp "$TARGET" "$TARGET.bak_$(date +%s)"

echo "🔧 Applying patch..."

# Insert after first <ScrollView
awk '
  /<ScrollView/ && !done {
    print $0
    print "        {/* Simple local build & paint tracker card */}"
    print "        <View"
    print "          style={{"
    print "            marginTop: 16,"
    print "            marginBottom: 16,"
    print "            padding: 16,"
    print "            borderRadius: 16,"
    print "            backgroundColor: \"#FFFFFF\","
    print "            shadowColor: \"#000000\","
    print "            shadowOpacity: 0.04,"
    print "            shadowRadius: 10,"
    print "            shadowOffset: { width: 0, height: 3 },"
    print "            elevation: 2,"
    print "          }}"
    print "        >"
    print "          <Text"
    print "            style={{ fontSize: 16, fontWeight: \"600\", color: \"#1A202C\", marginBottom: 4 }}"
    print "          >"
    print "            Build & paint tracker (DEBUG)"
    print "          </Text>"
    print ""
    print "          <Text"
    print "            style={{ fontSize: 13, color: \"#4A5568\", marginBottom: 12 }}"
    print "          >"
    print "            Use this to track a single active project – a Warhammer unit, Gunpla kit,"
    print "            or LEGO build. Later we can attach this to a specific project row."
    print "          </Text>"
    print ""
    print "          {/* Notes */}"
    print "          <Text"
    print "            style={{ fontSize: 13, fontWeight: \"600\", color: \"#2D3748\", marginBottom: 4 }}"
    print "          >"
    print "            Notes"
    print "          </Text>"
    print ""
    print "          <TextInput"
    print "            style={{"
    print "              borderRadius: 12,"
    print "              borderWidth: 1,"
    print "              borderColor: \"#E2E8F0\","
    print "              paddingHorizontal: 10,"
    print "              paddingVertical: 8,"
    print "              fontSize: 13,"
    print "              color: \"#1A202C\","
    print "              minHeight: 80,"
    print "              marginBottom: 12,"
    print "            }}"
    print "            placeholder=\"Example: Warm ivory armor, purple OSL on blade, oils for skin…\""
    print "            placeholderTextColor=\"#A0AEC0\""
    print "            multiline"
    print "            textAlignVertical=\"top\""
    print "          />"
    print ""
    print "          {/* Steps */}"
    print "          <Text"
    print "            style={{ fontSize: 13, fontWeight: \"600\", color: \"2D3748\", marginBottom: 6 }}"
    print "          >"
    print "            Progress steps"
    print "          </Text>"
    print ""
    print "          {["
    print "            \"Planning and references gathered\","
    print "            \"Assembly / build finished\","
    print "            \"Primed / surface prepared\","
    print "            \"Base layer / basecoat finished\","
    print "            \"Shading / washes done\","
    print "            \"Details and highlights finished\","
    print "            \"Final touches & varnish / display ready\","
    print "          ].map((label, idx) => ("
    print "            <View"
    print "              key={idx}"
    print "              style={{ flexDirection: \"row\", alignItems: \"center\", paddingVertical: 6 }}"
    print "            >"
    print "              <View"
    print "                style={{"
    print "                  width: 20,"
    print "                  height: 20,"
    print "                  borderRadius: 999,"
    print "                  borderWidth: 1,"
    print "                  borderColor: \"#CBD5E0\","
    print "                  marginRight: 8,"
    print "                }}"
    print "              />"
    print "              <Text style={{ flex: 1, fontSize: 13, color: \"#2D3748\" }} numberOfLines={2}>"
    print "                {label}"
    print "              </Text>"
    print "            </View>"
    print "          ))}"
    print ""
    print "          <Text style={{ marginTop: 10, fontSize: 11, color: \"#A0AEC0\" }}>"
    print "            This is local-only for now. Later we’ll hook it to Supabase projects and sessions."
    print "          </Text>"
    print "        </View>"
    done=1
    next
  }
  { print }
' "$TARGET" > "$TARGET.tmp"

mv "$TARGET.tmp" "$TARGET"

echo "✅ Patch applied successfully."
