#!/usr/bin/env python3
"""
Build a per-category attribute vocabulary from parsed catalog data.

Walks all `catalog_seed_v2.sql` files (generated by
`migrate_notes_to_attributes.py`) and produces a JSON vocabulary mapping:

    {
      "watches": {
        "brand": {"Rolex": 124, "Omega": 78, "Tudor": 32, ...},
        "case_material": {"Stainless Steel": 412, "18k Yellow Gold": 21, ...},
        ...
      },
      "pokemon": {
        "set_name": {"Base Set": 102, "Jungle": 64, ...},
        ...
      }
    }

This vocabulary is the ground-truth dictionary the QuickScan attribute
normalizer uses to snap fuzzy vision output to canonical values.

Usage:
    python -m pipelines.build_attribute_vocab
    # → writes server/data/_vocab/attribute_vocab.json
"""

from __future__ import annotations

import json
import re
import sys
from collections import defaultdict
from pathlib import Path
from typing import Any

DATA_DIR = Path(__file__).resolve().parent.parent / "data"
VOCAB_DIR = DATA_DIR / "_vocab"

# Match a value tuple from the v2 seeds. The last value is `attributes_json`.
_ROW_RE = re.compile(
    r"\(\s*'([^']*)'\s*,\s*"     # category
    r"'((?:[^']|'')*)'\s*,\s*"   # set_code
    r"'((?:[^']|'')*)'\s*,\s*"   # item_key
    r"'((?:[^']|'')*)'\s*,\s*"   # title
    r"'((?:[^']|'')*)'\s*,\s*"   # brand
    r"'((?:[^']|'')*)'\s*,\s*"   # rarity
    r"'((?:[^']|'')*)'\s*,\s*"   # notes
    r"'((?:[^']|'')*)'::jsonb\s*\)",  # attributes_json
    re.DOTALL,
)


def _unescape(s: str) -> str:
    return s.replace("''", "'")


def parse_v2_seed(path: Path) -> list[dict[str, Any]]:
    """Extract the attributes_json from each row in a v2 seed file."""
    text = path.read_text(encoding="utf-8")
    rows = []
    for m in _ROW_RE.finditer(text):
        category = _unescape(m.group(1))
        attrs_str = _unescape(m.group(8))
        try:
            attrs = json.loads(attrs_str) if attrs_str else {}
        except json.JSONDecodeError:
            continue
        rows.append({"category": category, "attributes": attrs})
    return rows


def build_vocab() -> dict[str, dict[str, dict[str, int]]]:
    """
    Build the full vocabulary by walking all v2 seed files.

    Returns: {category: {field_name: {value: count}}}
    """
    vocab: dict[str, dict[str, dict[str, int]]] = defaultdict(
        lambda: defaultdict(lambda: defaultdict(int))
    )

    seed_paths = sorted(DATA_DIR.glob("*/catalog_seed_v2.sql"))
    print(f"Found {len(seed_paths)} v2 seed files")

    total_rows = 0
    for seed_path in seed_paths:
        rows = parse_v2_seed(seed_path)
        for row in rows:
            cat = row["category"]
            for k, v in row["attributes"].items():
                # Only string/numeric values are useful for vocab matching
                if v is None or v == "":
                    continue
                key = str(v).strip()
                if key:
                    vocab[cat][k][key] += 1
        total_rows += len(rows)

    print(f"Processed {total_rows:,} rows")
    return {k: dict(v) for k, v in vocab.items()}


def main():
    print(f"\n{'='*60}")
    print(f"  BUILDING ATTRIBUTE VOCABULARY")
    print(f"{'='*60}\n")

    vocab = build_vocab()

    # Stats
    total_categories = len(vocab)
    total_fields = sum(len(fields) for fields in vocab.values())
    total_unique_values = sum(
        len(values)
        for fields in vocab.values()
        for values in fields.values()
    )

    print(f"\nVocabulary built:")
    print(f"  Categories:      {total_categories}")
    print(f"  Fields total:    {total_fields}")
    print(f"  Unique values:   {total_unique_values:,}")

    # Per-category breakdown (top 10 by field count)
    by_field_count = sorted(vocab.items(), key=lambda x: -len(x[1]))
    print(f"\nTop categories by field count:")
    for cat, fields in by_field_count[:10]:
        n_values = sum(len(v) for v in fields.values())
        print(f"  {cat:25s}  {len(fields):3d} fields  {n_values:6,} unique values")

    # Convert defaultdict structure to plain dict for JSON serialization
    serializable: dict[str, Any] = {}
    for cat, fields in vocab.items():
        serializable[cat] = {
            field: dict(values)
            for field, values in fields.items()
        }

    # Write to disk
    VOCAB_DIR.mkdir(parents=True, exist_ok=True)
    out = VOCAB_DIR / "attribute_vocab.json"
    out.write_text(json.dumps(serializable, indent=2, ensure_ascii=False), encoding="utf-8")
    print(f"\nWritten: {out.relative_to(DATA_DIR.parent)}")
    print(f"Size: {out.stat().st_size / 1024:.1f} KB")


if __name__ == "__main__":
    main()
