-- Jewellery catalogue seed — 2026-08-11 · 317 rows, 41 maisons
--
-- REVIEW BEFORE RUNNING. Curated from knowledge of each maison's product lines,
-- not from any source. If a line name or material is wrong, no gate can catch
-- it — that check is yours.
--
-- SCOPE: designer / high-ASP maisons only. Pandora and Swarovski were REMOVED as
-- mass-market (Merle, 2026-08-11).
--
-- FASHION HOUSES ARE LINE-ANCHORED, NOT BARE. Chanel, Dior, Hermès, Louis
-- Vuitton and Gucci sell bags, clothing and watches. The classifier matches
-- "Chanel Coco Crush" and NOT "Chanel Classic Flap" or "Chanel J12" — measured
-- against 6,902 real catalogue titles, 0 false positives.
--
-- NAME-ONLY, NO REFERENCE NUMBERS. The 1,416 `watches` rows carry real refs
-- (126500LN); jewellery maisons do not publish equivalents, so inventing them
-- would make these rows look as authoritative as the watch rows without being so.
--
-- THESE ROWS CANNOT BE PRICED. No sold-comp source, same as watches. Renders as
-- "not yet priced" since the 2026-08-10 median/spread change.
--
-- TAGGING: source='seed' (matches watches; catalog_browser_router.py never reads
-- it), verified=false, notes=the maison's line, attributes_json carries the
-- seed_batch marker. Etoile rows also carry status=archived.
--
-- IDEMPOTENT on (category, item_key).

BEGIN;

INSERT INTO category_items (category, item_key, title, brand, notes, source, verified, attributes_json)
VALUES
  ('jewellery','tiffany-and-co-tiffany-t-smile-pendant-18k-rose-gold','Tiffany T Smile Pendant, 18k Rose Gold','Tiffany & Co.','T','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','tiffany-and-co-tiffany-t-smile-pendant-18k-yellow-gold','Tiffany T Smile Pendant, 18k Yellow Gold','Tiffany & Co.','T','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','tiffany-and-co-tiffany-t-smile-pendant-18k-white-gold-with-diamonds','Tiffany T Smile Pendant, 18k White Gold with Diamonds','Tiffany & Co.','T','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','tiffany-and-co-tiffany-t1-ring-18k-rose-gold','Tiffany T1 Ring, 18k Rose Gold','Tiffany & Co.','T','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','tiffany-and-co-tiffany-t1-wide-ring-18k-yellow-gold','Tiffany T1 Wide Ring, 18k Yellow Gold','Tiffany & Co.','T','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','tiffany-and-co-tiffany-t1-hinged-bangle-18k-rose-gold','Tiffany T1 Hinged Bangle, 18k Rose Gold','Tiffany & Co.','T','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','tiffany-and-co-tiffany-t-wire-bracelet-18k-yellow-gold','Tiffany T Wire Bracelet, 18k Yellow Gold','Tiffany & Co.','T','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','tiffany-and-co-tiffany-t-true-ring-18k-white-gold','Tiffany T True Ring, 18k White Gold','Tiffany & Co.','T','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','tiffany-and-co-tiffany-t-chain-bracelet-18k-yellow-gold','Tiffany T Chain Bracelet, 18k Yellow Gold','Tiffany & Co.','T','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','tiffany-and-co-tiffany-etoile-band-ring-platinum','Tiffany Etoile Band Ring, Platinum','Tiffany & Co.','Etoile','seed',false,'{"seed_batch": "jewellery_2026_08_11", "line": "etoile", "status": "archived"}'::jsonb),
  ('jewellery','tiffany-and-co-tiffany-etoile-band-ring-18k-yellow-gold','Tiffany Etoile Band Ring, 18k Yellow Gold','Tiffany & Co.','Etoile','seed',false,'{"seed_batch": "jewellery_2026_08_11", "line": "etoile", "status": "archived"}'::jsonb),
  ('jewellery','tiffany-and-co-tiffany-etoile-diamond-band-platinum','Tiffany Etoile Diamond Band, Platinum','Tiffany & Co.','Etoile','seed',false,'{"seed_batch": "jewellery_2026_08_11", "line": "etoile", "status": "archived"}'::jsonb),
  ('jewellery','tiffany-and-co-tiffany-etoile-engagement-ring-platinum','Tiffany Etoile Engagement Ring, Platinum','Tiffany & Co.','Etoile','seed',false,'{"seed_batch": "jewellery_2026_08_11", "line": "etoile", "status": "archived"}'::jsonb),
  ('jewellery','tiffany-and-co-tiffany-etoile-eternity-band-platinum','Tiffany Etoile Eternity Band, Platinum','Tiffany & Co.','Etoile','seed',false,'{"seed_batch": "jewellery_2026_08_11", "line": "etoile", "status": "archived"}'::jsonb),
  ('jewellery','tiffany-and-co-tiffany-etoile-bangle-18k-yellow-gold','Tiffany Etoile Bangle, 18k Yellow Gold','Tiffany & Co.','Etoile','seed',false,'{"seed_batch": "jewellery_2026_08_11", "line": "etoile", "status": "archived"}'::jsonb),
  ('jewellery','tiffany-and-co-tiffany-etoile-earrings-platinum-with-diamonds','Tiffany Etoile Earrings, Platinum with Diamonds','Tiffany & Co.','Etoile','seed',false,'{"seed_batch": "jewellery_2026_08_11", "line": "etoile", "status": "archived"}'::jsonb),
  ('jewellery','tiffany-and-co-tiffany-hardwear-graduated-link-necklace-sterling-silver','Tiffany HardWear Graduated Link Necklace, Sterling Silver','Tiffany & Co.','HardWear','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','tiffany-and-co-tiffany-hardwear-large-link-bracelet-18k-yellow-gold','Tiffany HardWear Large Link Bracelet, 18k Yellow Gold','Tiffany & Co.','HardWear','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','tiffany-and-co-tiffany-hardwear-ball-bracelet-sterling-silver','Tiffany HardWear Ball Bracelet, Sterling Silver','Tiffany & Co.','HardWear','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','tiffany-and-co-tiffany-hardwear-wrap-necklace-sterling-silver','Tiffany HardWear Wrap Necklace, Sterling Silver','Tiffany & Co.','HardWear','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','tiffany-and-co-tiffany-hardwear-link-earrings-18k-rose-gold','Tiffany HardWear Link Earrings, 18k Rose Gold','Tiffany & Co.','HardWear','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','tiffany-and-co-return-to-tiffany-heart-tag-bracelet-sterling-silver','Return to Tiffany Heart Tag Bracelet, Sterling Silver','Tiffany & Co.','Return to Tiffany','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','tiffany-and-co-return-to-tiffany-heart-tag-pendant-sterling-silver','Return to Tiffany Heart Tag Pendant, Sterling Silver','Tiffany & Co.','Return to Tiffany','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','tiffany-and-co-return-to-tiffany-love-bugs-pendant-sterling-silver','Return to Tiffany Love Bugs Pendant, Sterling Silver','Tiffany & Co.','Return to Tiffany','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','tiffany-and-co-return-to-tiffany-oval-tag-necklace-sterling-silver','Return to Tiffany Oval Tag Necklace, Sterling Silver','Tiffany & Co.','Return to Tiffany','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','tiffany-and-co-tiffany-knot-double-row-ring-18k-yellow-gold','Tiffany Knot Double Row Ring, 18k Yellow Gold','Tiffany & Co.','Knot','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','tiffany-and-co-tiffany-knot-hinged-bangle-18k-rose-gold','Tiffany Knot Hinged Bangle, 18k Rose Gold','Tiffany & Co.','Knot','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','tiffany-and-co-tiffany-knot-pendant-18k-white-gold-with-diamonds','Tiffany Knot Pendant, 18k White Gold with Diamonds','Tiffany & Co.','Knot','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','tiffany-and-co-tiffany-knot-earrings-18k-yellow-gold','Tiffany Knot Earrings, 18k Yellow Gold','Tiffany & Co.','Knot','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','tiffany-and-co-elsa-peretti-open-heart-pendant-sterling-silver','Elsa Peretti Open Heart Pendant, Sterling Silver','Tiffany & Co.','Elsa Peretti','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','tiffany-and-co-elsa-peretti-bone-cuff-sterling-silver','Elsa Peretti Bone Cuff, Sterling Silver','Tiffany & Co.','Elsa Peretti','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','tiffany-and-co-elsa-peretti-diamonds-by-the-yard-necklace-platinum','Elsa Peretti Diamonds by the Yard Necklace, Platinum','Tiffany & Co.','Elsa Peretti','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','tiffany-and-co-elsa-peretti-bean-design-pendant-sterling-silver','Elsa Peretti Bean Design Pendant, Sterling Silver','Tiffany & Co.','Elsa Peretti','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','tiffany-and-co-elsa-peretti-teardrop-earrings-sterling-silver','Elsa Peretti Teardrop Earrings, Sterling Silver','Tiffany & Co.','Elsa Peretti','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','tiffany-and-co-elsa-peretti-full-heart-pendant-18k-yellow-gold','Elsa Peretti Full Heart Pendant, 18k Yellow Gold','Tiffany & Co.','Elsa Peretti','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','tiffany-and-co-elsa-peretti-mesh-scarf-necklace-sterling-silver','Elsa Peretti Mesh Scarf Necklace, Sterling Silver','Tiffany & Co.','Elsa Peretti','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','tiffany-and-co-paloma-picasso-loving-heart-pendant-sterling-silver','Paloma Picasso Loving Heart Pendant, Sterling Silver','Tiffany & Co.','Paloma Picasso','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','tiffany-and-co-paloma-picasso-olive-leaf-band-ring-18k-yellow-gold','Paloma Picasso Olive Leaf Band Ring, 18k Yellow Gold','Tiffany & Co.','Paloma Picasso','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','tiffany-and-co-paloma-picasso-graffiti-love-pendant-sterling-silver','Paloma Picasso Graffiti Love Pendant, Sterling Silver','Tiffany & Co.','Paloma Picasso','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','tiffany-and-co-the-tiffany-setting-engagement-ring-platinum','The Tiffany Setting Engagement Ring, Platinum','Tiffany & Co.','The Tiffany Setting','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','tiffany-and-co-the-tiffany-setting-engagement-ring-18k-yellow-gold','The Tiffany Setting Engagement Ring, 18k Yellow Gold','Tiffany & Co.','The Tiffany Setting','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','tiffany-and-co-tiffany-victoria-line-pendant-platinum','Tiffany Victoria Line Pendant, Platinum','Tiffany & Co.','Victoria','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','tiffany-and-co-tiffany-victoria-cluster-earrings-platinum','Tiffany Victoria Cluster Earrings, Platinum','Tiffany & Co.','Victoria','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','tiffany-and-co-tiffany-victoria-vine-bracelet-platinum','Tiffany Victoria Vine Bracelet, Platinum','Tiffany & Co.','Victoria','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','tiffany-and-co-tiffany-soleste-halo-ring-platinum','Tiffany Soleste Halo Ring, Platinum','Tiffany & Co.','Soleste','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','tiffany-and-co-tiffany-soleste-pendant-18k-rose-gold','Tiffany Soleste Pendant, 18k Rose Gold','Tiffany & Co.','Soleste','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','tiffany-and-co-tiffany-atlas-pierced-ring-18k-white-gold','Tiffany Atlas Pierced Ring, 18k White Gold','Tiffany & Co.','Atlas','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','tiffany-and-co-tiffany-atlas-x-hinged-bangle-sterling-silver','Tiffany Atlas X Hinged Bangle, Sterling Silver','Tiffany & Co.','Atlas','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','tiffany-and-co-tiffany-lock-bangle-18k-rose-gold','Tiffany Lock Bangle, 18k Rose Gold','Tiffany & Co.','Lock','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','tiffany-and-co-tiffany-lock-bangle-18k-yellow-gold-with-diamonds','Tiffany Lock Bangle, 18k Yellow Gold with Diamonds','Tiffany & Co.','Lock','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','tiffany-and-co-tiffany-lock-pendant-18k-yellow-gold','Tiffany Lock Pendant, 18k Yellow Gold','Tiffany & Co.','Lock','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','tiffany-and-co-schlumberger-sixteen-stone-ring-platinum-and-18k-gold','Schlumberger Sixteen Stone Ring, Platinum and 18k Gold','Tiffany & Co.','Jean Schlumberger','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','tiffany-and-co-schlumberger-bird-on-a-rock-brooch-18k-yellow-gold','Schlumberger Bird on a Rock Brooch, 18k Yellow Gold','Tiffany & Co.','Jean Schlumberger','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','tiffany-and-co-schlumberger-rope-two-row-bracelet-18k-yellow-gold','Schlumberger Rope Two-Row Bracelet, 18k Yellow Gold','Tiffany & Co.','Jean Schlumberger','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','cartier-cartier-love-bracelet-18k-yellow-gold','Cartier Love Bracelet, 18k Yellow Gold','Cartier','Love','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','cartier-cartier-love-bracelet-18k-white-gold','Cartier Love Bracelet, 18k White Gold','Cartier','Love','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','cartier-cartier-love-bracelet-18k-rose-gold','Cartier Love Bracelet, 18k Rose Gold','Cartier','Love','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','cartier-cartier-love-bracelet-18k-rose-gold-with-diamonds','Cartier Love Bracelet, 18k Rose Gold with Diamonds','Cartier','Love','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','cartier-cartier-love-small-bracelet-18k-yellow-gold','Cartier Love Small Bracelet, 18k Yellow Gold','Cartier','Love','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','cartier-cartier-love-ring-18k-yellow-gold','Cartier Love Ring, 18k Yellow Gold','Cartier','Love','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','cartier-cartier-love-ring-18k-white-gold-with-diamonds','Cartier Love Ring, 18k White Gold with Diamonds','Cartier','Love','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','cartier-cartier-love-wedding-band-platinum','Cartier Love Wedding Band, Platinum','Cartier','Love','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','cartier-cartier-love-necklace-18k-rose-gold','Cartier Love Necklace, 18k Rose Gold','Cartier','Love','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','cartier-cartier-love-earrings-18k-yellow-gold','Cartier Love Earrings, 18k Yellow Gold','Cartier','Love','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','cartier-cartier-love-cuff-18k-yellow-gold','Cartier Love Cuff, 18k Yellow Gold','Cartier','Love','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','cartier-cartier-juste-un-clou-bracelet-18k-yellow-gold','Cartier Juste un Clou Bracelet, 18k Yellow Gold','Cartier','Juste un Clou','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','cartier-cartier-juste-un-clou-bracelet-18k-rose-gold-with-diamonds','Cartier Juste un Clou Bracelet, 18k Rose Gold with Diamonds','Cartier','Juste un Clou','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','cartier-cartier-juste-un-clou-small-bracelet-18k-white-gold','Cartier Juste un Clou Small Bracelet, 18k White Gold','Cartier','Juste un Clou','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','cartier-cartier-juste-un-clou-ring-18k-rose-gold','Cartier Juste un Clou Ring, 18k Rose Gold','Cartier','Juste un Clou','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','cartier-cartier-juste-un-clou-necklace-18k-white-gold','Cartier Juste un Clou Necklace, 18k White Gold','Cartier','Juste un Clou','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','cartier-cartier-juste-un-clou-earrings-18k-yellow-gold','Cartier Juste un Clou Earrings, 18k Yellow Gold','Cartier','Juste un Clou','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','cartier-cartier-trinity-ring-three-gold','Cartier Trinity Ring, Three-Gold','Cartier','Trinity','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','cartier-cartier-trinity-large-ring-three-gold','Cartier Trinity Large Ring, Three-Gold','Cartier','Trinity','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','cartier-cartier-trinity-bracelet-three-gold','Cartier Trinity Bracelet, Three-Gold','Cartier','Trinity','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','cartier-cartier-trinity-necklace-three-gold','Cartier Trinity Necklace, Three-Gold','Cartier','Trinity','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','cartier-cartier-trinity-cushion-ring-three-gold','Cartier Trinity Cushion Ring, Three-Gold','Cartier','Trinity','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','cartier-cartier-trinity-earrings-three-gold','Cartier Trinity Earrings, Three-Gold','Cartier','Trinity','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','cartier-clash-de-cartier-ring-18k-rose-gold','Clash de Cartier Ring, 18k Rose Gold','Cartier','Clash','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','cartier-clash-de-cartier-bracelet-18k-white-gold','Clash de Cartier Bracelet, 18k White Gold','Cartier','Clash','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','cartier-clash-de-cartier-earrings-18k-rose-gold','Clash de Cartier Earrings, 18k Rose Gold','Cartier','Clash','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','cartier-clash-de-cartier-necklace-18k-yellow-gold','Clash de Cartier Necklace, 18k Yellow Gold','Cartier','Clash','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','cartier-panth-re-de-cartier-ring-18k-yellow-gold','Panthère de Cartier Ring, 18k Yellow Gold','Cartier','Panthère','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','cartier-panth-re-de-cartier-necklace-18k-white-gold','Panthère de Cartier Necklace, 18k White Gold','Cartier','Panthère','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','cartier-panth-re-de-cartier-bracelet-18k-yellow-gold-with-emeralds','Panthère de Cartier Bracelet, 18k Yellow Gold with Emeralds','Cartier','Panthère','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','cartier-ecrou-de-cartier-bracelet-18k-rose-gold','Ecrou de Cartier Bracelet, 18k Rose Gold','Cartier','Ecrou','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','cartier-ecrou-de-cartier-ring-18k-yellow-gold','Ecrou de Cartier Ring, 18k Yellow Gold','Cartier','Ecrou','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','cartier-agrafe-de-cartier-ring-18k-rose-gold','Agrafe de Cartier Ring, 18k Rose Gold','Cartier','Agrafe','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','cartier-grain-de-caf-bracelet-18k-yellow-gold','Grain de Café Bracelet, 18k Yellow Gold','Cartier','Grain de Café','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','cartier-cactus-de-cartier-ring-18k-yellow-gold','Cactus de Cartier Ring, 18k Yellow Gold','Cartier','Cactus','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','van-cleef-and-arpels-vintage-alhambra-bracelet-5-motifs-yellow-gold','Vintage Alhambra Bracelet, 5 Motifs, Yellow Gold','Van Cleef & Arpels','Alhambra','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','van-cleef-and-arpels-vintage-alhambra-bracelet-5-motifs-mother-of-pearl','Vintage Alhambra Bracelet, 5 Motifs, Mother-of-Pearl','Van Cleef & Arpels','Alhambra','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','van-cleef-and-arpels-vintage-alhambra-bracelet-5-motifs-onyx','Vintage Alhambra Bracelet, 5 Motifs, Onyx','Van Cleef & Arpels','Alhambra','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','van-cleef-and-arpels-vintage-alhambra-necklace-10-motifs-yellow-gold','Vintage Alhambra Necklace, 10 Motifs, Yellow Gold','Van Cleef & Arpels','Alhambra','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','van-cleef-and-arpels-vintage-alhambra-necklace-20-motifs-yellow-gold','Vintage Alhambra Necklace, 20 Motifs, Yellow Gold','Van Cleef & Arpels','Alhambra','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','van-cleef-and-arpels-vintage-alhambra-necklace-10-motifs-carnelian','Vintage Alhambra Necklace, 10 Motifs, Carnelian','Van Cleef & Arpels','Alhambra','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','van-cleef-and-arpels-vintage-alhambra-necklace-10-motifs-malachite','Vintage Alhambra Necklace, 10 Motifs, Malachite','Van Cleef & Arpels','Alhambra','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','van-cleef-and-arpels-vintage-alhambra-pendant-mother-of-pearl','Vintage Alhambra Pendant, Mother-of-Pearl','Van Cleef & Arpels','Alhambra','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','van-cleef-and-arpels-vintage-alhambra-pendant-onyx','Vintage Alhambra Pendant, Onyx','Van Cleef & Arpels','Alhambra','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','van-cleef-and-arpels-vintage-alhambra-earrings-malachite','Vintage Alhambra Earrings, Malachite','Van Cleef & Arpels','Alhambra','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','van-cleef-and-arpels-vintage-alhambra-earrings-mother-of-pearl','Vintage Alhambra Earrings, Mother-of-Pearl','Van Cleef & Arpels','Alhambra','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','van-cleef-and-arpels-vintage-alhambra-ring-grey-mother-of-pearl','Vintage Alhambra Ring, Grey Mother-of-Pearl','Van Cleef & Arpels','Alhambra','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','van-cleef-and-arpels-sweet-alhambra-bracelet-carnelian','Sweet Alhambra Bracelet, Carnelian','Van Cleef & Arpels','Sweet Alhambra','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','van-cleef-and-arpels-sweet-alhambra-pendant-mother-of-pearl','Sweet Alhambra Pendant, Mother-of-Pearl','Van Cleef & Arpels','Sweet Alhambra','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','van-cleef-and-arpels-sweet-alhambra-earstuds-onyx','Sweet Alhambra Earstuds, Onyx','Van Cleef & Arpels','Sweet Alhambra','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','van-cleef-and-arpels-magic-alhambra-long-necklace-onyx','Magic Alhambra Long Necklace, Onyx','Van Cleef & Arpels','Magic Alhambra','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','van-cleef-and-arpels-magic-alhambra-earrings-grey-mother-of-pearl','Magic Alhambra Earrings, Grey Mother-of-Pearl','Van Cleef & Arpels','Magic Alhambra','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','van-cleef-and-arpels-magic-alhambra-pendant-yellow-gold','Magic Alhambra Pendant, Yellow Gold','Van Cleef & Arpels','Magic Alhambra','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','van-cleef-and-arpels-lucky-alhambra-bracelet-butterfly-motif','Lucky Alhambra Bracelet, Butterfly Motif','Van Cleef & Arpels','Lucky Alhambra','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','van-cleef-and-arpels-lucky-alhambra-long-necklace-mixed-motifs','Lucky Alhambra Long Necklace, Mixed Motifs','Van Cleef & Arpels','Lucky Alhambra','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','van-cleef-and-arpels-frivole-earrings-18k-yellow-gold','Frivole Earrings, 18k Yellow Gold','Van Cleef & Arpels','Frivole','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','van-cleef-and-arpels-frivole-pendant-18k-yellow-gold','Frivole Pendant, 18k Yellow Gold','Van Cleef & Arpels','Frivole','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','van-cleef-and-arpels-frivole-between-the-finger-ring-18k-yellow-gold','Frivole Between the Finger Ring, 18k Yellow Gold','Van Cleef & Arpels','Frivole','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','van-cleef-and-arpels-frivole-bracelet-9-flowers-18k-yellow-gold','Frivole Bracelet, 9 Flowers, 18k Yellow Gold','Van Cleef & Arpels','Frivole','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','van-cleef-and-arpels-perl-e-clovers-bracelet-18k-rose-gold','Perlée Clovers Bracelet, 18k Rose Gold','Van Cleef & Arpels','Perlée','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','van-cleef-and-arpels-perl-e-signature-ring-18k-yellow-gold','Perlée Signature Ring, 18k Yellow Gold','Van Cleef & Arpels','Perlée','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','van-cleef-and-arpels-perl-e-pearls-of-gold-bracelet-18k-white-gold','Perlée Pearls of Gold Bracelet, 18k White Gold','Van Cleef & Arpels','Perlée','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','van-cleef-and-arpels-perl-e-diamonds-bangle-18k-white-gold','Perlée Diamonds Bangle, 18k White Gold','Van Cleef & Arpels','Perlée','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','van-cleef-and-arpels-two-butterfly-pendant-18k-white-gold-with-diamonds','Two Butterfly Pendant, 18k White Gold with Diamonds','Van Cleef & Arpels','Two Butterfly','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','van-cleef-and-arpels-two-butterfly-between-the-finger-ring-18k-rose-gold','Two Butterfly Between the Finger Ring, 18k Rose Gold','Van Cleef & Arpels','Two Butterfly','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','van-cleef-and-arpels-zodiaque-medal-pendant-18k-yellow-gold','Zodiaque Medal Pendant, 18k Yellow Gold','Van Cleef & Arpels','Zodiaque','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','bulgari-bulgari-b-zero1-ring-18k-rose-gold','Bulgari B.zero1 Ring, 18k Rose Gold','Bulgari','B.zero1','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','bulgari-bulgari-b-zero1-ring-18k-yellow-gold-4-band','Bulgari B.zero1 Ring, 18k Yellow Gold, 4-Band','Bulgari','B.zero1','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','bulgari-bulgari-b-zero1-necklace-18k-yellow-gold','Bulgari B.zero1 Necklace, 18k Yellow Gold','Bulgari','B.zero1','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','bulgari-bulgari-b-zero1-bracelet-18k-rose-gold','Bulgari B.zero1 Bracelet, 18k Rose Gold','Bulgari','B.zero1','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','bulgari-bulgari-b-zero1-rock-ring-18k-rose-gold-with-studs','Bulgari B.zero1 Rock Ring, 18k Rose Gold with Studs','Bulgari','B.zero1','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','bulgari-bulgari-b-zero1-earrings-18k-rose-gold','Bulgari B.zero1 Earrings, 18k Rose Gold','Bulgari','B.zero1','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','bulgari-bulgari-serpenti-viper-bracelet-18k-rose-gold','Bulgari Serpenti Viper Bracelet, 18k Rose Gold','Bulgari','Serpenti','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','bulgari-bulgari-serpenti-viper-ring-18k-white-gold-with-diamonds','Bulgari Serpenti Viper Ring, 18k White Gold with Diamonds','Bulgari','Serpenti','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','bulgari-bulgari-serpenti-viper-necklace-18k-rose-gold','Bulgari Serpenti Viper Necklace, 18k Rose Gold','Bulgari','Serpenti','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','bulgari-bulgari-serpenti-viper-earrings-18k-yellow-gold','Bulgari Serpenti Viper Earrings, 18k Yellow Gold','Bulgari','Serpenti','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','bulgari-bulgari-divas-dream-pendant-18k-rose-gold','Bulgari Divas'' Dream Pendant, 18k Rose Gold','Bulgari','Divas'' Dream','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','bulgari-bulgari-divas-dream-earrings-18k-rose-gold-with-mother-of-pearl','Bulgari Divas'' Dream Earrings, 18k Rose Gold with Mother-of-Pearl','Bulgari','Divas'' Dream','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','bulgari-bulgari-divas-dream-ring-18k-white-gold','Bulgari Divas'' Dream Ring, 18k White Gold','Bulgari','Divas'' Dream','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','bulgari-bulgari-monete-pendant-18k-yellow-gold-with-ancient-coin','Bulgari Monete Pendant, 18k Yellow Gold with Ancient Coin','Bulgari','Monete','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','bulgari-bulgari-monete-bracelet-18k-yellow-gold','Bulgari Monete Bracelet, 18k Yellow Gold','Bulgari','Monete','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','bulgari-bulgari-bulgari-ring-18k-yellow-gold','Bulgari Bulgari Ring, 18k Yellow Gold','Bulgari','Bulgari Bulgari','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','bulgari-bulgari-bulgari-pendant-18k-rose-gold','Bulgari Bulgari Pendant, 18k Rose Gold','Bulgari','Bulgari Bulgari','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','bulgari-bulgari-fiorever-pendant-18k-rose-gold-with-diamond','Bulgari Fiorever Pendant, 18k Rose Gold with Diamond','Bulgari','Fiorever','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','bulgari-bulgari-fiorever-earrings-18k-white-gold','Bulgari Fiorever Earrings, 18k White Gold','Bulgari','Fiorever','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','bulgari-bulgari-parentesi-bracelet-18k-yellow-gold','Bulgari Parentesi Bracelet, 18k Yellow Gold','Bulgari','Parentesi','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','de-beers-de-beers-enchanted-lotus-pendant-18k-white-gold','De Beers Enchanted Lotus Pendant, 18k White Gold','De Beers','Enchanted Lotus','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','de-beers-de-beers-enchanted-lotus-bracelet-18k-rose-gold','De Beers Enchanted Lotus Bracelet, 18k Rose Gold','De Beers','Enchanted Lotus','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','de-beers-de-beers-enchanted-lotus-earrings-18k-white-gold','De Beers Enchanted Lotus Earrings, 18k White Gold','De Beers','Enchanted Lotus','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','de-beers-de-beers-enchanted-lotus-ring-18k-yellow-gold','De Beers Enchanted Lotus Ring, 18k Yellow Gold','De Beers','Enchanted Lotus','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','de-beers-de-beers-aura-solitaire-ring-platinum','De Beers Aura Solitaire Ring, Platinum','De Beers','Aura','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','de-beers-de-beers-aura-pendant-18k-white-gold','De Beers Aura Pendant, 18k White Gold','De Beers','Aura','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','de-beers-de-beers-aura-stud-earrings-18k-white-gold','De Beers Aura Stud Earrings, 18k White Gold','De Beers','Aura','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','de-beers-de-beers-talisman-pendant-18k-yellow-gold-with-rough-diamonds','De Beers Talisman Pendant, 18k Yellow Gold with Rough Diamonds','De Beers','Talisman','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','de-beers-de-beers-talisman-ring-18k-yellow-gold','De Beers Talisman Ring, 18k Yellow Gold','De Beers','Talisman','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','de-beers-de-beers-talisman-medium-pendant-18k-white-gold','De Beers Talisman Medium Pendant, 18k White Gold','De Beers','Talisman','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','de-beers-de-beers-db-classic-eternity-band-platinum','De Beers DB Classic Eternity Band, Platinum','De Beers','DB Classic','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','de-beers-de-beers-db-classic-solitaire-pendant-18k-white-gold','De Beers DB Classic Solitaire Pendant, 18k White Gold','De Beers','DB Classic','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','de-beers-de-beers-adonis-rose-necklace-18k-white-gold','De Beers Adonis Rose Necklace, 18k White Gold','De Beers','Adonis Rose','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','de-beers-de-beers-adonis-rose-bracelet-18k-white-gold','De Beers Adonis Rose Bracelet, 18k White Gold','De Beers','Adonis Rose','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','de-beers-de-beers-dewdrop-earrings-18k-white-gold','De Beers Dewdrop Earrings, 18k White Gold','De Beers','Dewdrop','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','de-beers-de-beers-dewdrop-necklace-18k-rose-gold','De Beers Dewdrop Necklace, 18k Rose Gold','De Beers','Dewdrop','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','messika-messika-move-classique-bracelet-18k-white-gold','Messika Move Classique Bracelet, 18k White Gold','Messika','Move','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','messika-messika-move-classique-ring-18k-rose-gold','Messika Move Classique Ring, 18k Rose Gold','Messika','Move','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','messika-messika-move-classique-necklace-18k-yellow-gold','Messika Move Classique Necklace, 18k Yellow Gold','Messika','Move','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','messika-messika-move-romane-bracelet-18k-rose-gold','Messika Move Romane Bracelet, 18k Rose Gold','Messika','Move','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','messika-messika-move-romane-necklace-18k-white-gold','Messika Move Romane Necklace, 18k White Gold','Messika','Move','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','messika-messika-move-romane-ring-18k-yellow-gold','Messika Move Romane Ring, 18k Yellow Gold','Messika','Move','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','messika-messika-move-uno-ring-18k-yellow-gold','Messika Move Uno Ring, 18k Yellow Gold','Messika','Move','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','messika-messika-move-uno-bracelet-18k-white-gold','Messika Move Uno Bracelet, 18k White Gold','Messika','Move','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','messika-messika-move-uno-necklace-18k-rose-gold','Messika Move Uno Necklace, 18k Rose Gold','Messika','Move','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','messika-messika-move-noa-pendant-18k-rose-gold','Messika Move Noa Pendant, 18k Rose Gold','Messika','Move','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','messika-messika-move-link-bracelet-18k-white-gold','Messika Move Link Bracelet, 18k White Gold','Messika','Move','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','messika-messika-lucky-move-necklace-18k-rose-gold-with-mother-of-pearl','Messika Lucky Move Necklace, 18k Rose Gold with Mother-of-Pearl','Messika','Lucky Move','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','messika-messika-lucky-move-ring-18k-white-gold','Messika Lucky Move Ring, 18k White Gold','Messika','Lucky Move','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','messika-messika-lucky-move-bracelet-18k-yellow-gold','Messika Lucky Move Bracelet, 18k Yellow Gold','Messika','Lucky Move','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','messika-messika-baby-move-pendant-18k-rose-gold','Messika Baby Move Pendant, 18k Rose Gold','Messika','Baby Move','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','messika-messika-baby-move-ring-18k-white-gold','Messika Baby Move Ring, 18k White Gold','Messika','Baby Move','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','messika-messika-so-move-earrings-18k-white-gold','Messika So Move Earrings, 18k White Gold','Messika','So Move','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','messika-messika-so-move-pendant-18k-rose-gold','Messika So Move Pendant, 18k Rose Gold','Messika','So Move','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','messika-messika-gatsby-bracelet-18k-white-gold','Messika Gatsby Bracelet, 18k White Gold','Messika','Gatsby','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','graff-graff-butterfly-pendant-18k-white-gold-with-diamonds','Graff Butterfly Pendant, 18k White Gold with Diamonds','Graff','Butterfly','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','graff-graff-butterfly-earrings-18k-white-gold','Graff Butterfly Earrings, 18k White Gold','Graff','Butterfly','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','graff-graff-butterfly-ring-18k-rose-gold','Graff Butterfly Ring, 18k Rose Gold','Graff','Butterfly','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','graff-graff-wild-flower-ring-platinum','Graff Wild Flower Ring, Platinum','Graff','Wild Flower','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','graff-graff-wild-flower-earrings-18k-white-gold','Graff Wild Flower Earrings, 18k White Gold','Graff','Wild Flower','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','graff-graff-spiral-bracelet-18k-white-gold','Graff Spiral Bracelet, 18k White Gold','Graff','Spiral','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','graff-graff-icon-solitaire-ring-platinum','Graff Icon Solitaire Ring, Platinum','Graff','Icon','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','harry-winston-harry-winston-cluster-earrings-platinum','Harry Winston Cluster Earrings, Platinum','Harry Winston','Cluster','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','harry-winston-harry-winston-lily-cluster-pendant-18k-yellow-gold','Harry Winston Lily Cluster Pendant, 18k Yellow Gold','Harry Winston','Lily Cluster','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','harry-winston-harry-winston-lily-cluster-earrings-18k-rose-gold','Harry Winston Lily Cluster Earrings, 18k Rose Gold','Harry Winston','Lily Cluster','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','harry-winston-harry-winston-winston-cluster-ring-platinum','Harry Winston Winston Cluster Ring, Platinum','Harry Winston','Winston Cluster','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','harry-winston-harry-winston-sunflower-bracelet-18k-white-gold','Harry Winston Sunflower Bracelet, 18k White Gold','Harry Winston','Sunflower','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','harry-winston-harry-winston-sunflower-pendant-18k-yellow-gold','Harry Winston Sunflower Pendant, 18k Yellow Gold','Harry Winston','Sunflower','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','harry-winston-harry-winston-hw-logo-pendant-18k-rose-gold','Harry Winston HW Logo Pendant, 18k Rose Gold','Harry Winston','HW Logo','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','boucheron-boucheron-serpent-boh-me-pendant-18k-yellow-gold','Boucheron Serpent Bohème Pendant, 18k Yellow Gold','Boucheron','Serpent Bohème','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','boucheron-boucheron-serpent-boh-me-ring-18k-rose-gold','Boucheron Serpent Bohème Ring, 18k Rose Gold','Boucheron','Serpent Bohème','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','boucheron-boucheron-serpent-boh-me-earrings-18k-white-gold','Boucheron Serpent Bohème Earrings, 18k White Gold','Boucheron','Serpent Bohème','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','boucheron-boucheron-quatre-classique-ring-three-gold','Boucheron Quatre Classique Ring, Three-Gold','Boucheron','Quatre','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','boucheron-boucheron-quatre-radiant-bracelet-18k-yellow-gold','Boucheron Quatre Radiant Bracelet, 18k Yellow Gold','Boucheron','Quatre','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','boucheron-boucheron-quatre-white-edition-ring-18k-white-gold','Boucheron Quatre White Edition Ring, 18k White Gold','Boucheron','Quatre','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','boucheron-boucheron-jack-de-boucheron-necklace-18k-yellow-gold','Boucheron Jack de Boucheron Necklace, 18k Yellow Gold','Boucheron','Jack','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','chaumet-chaumet-bee-my-love-bracelet-18k-rose-gold','Chaumet Bee My Love Bracelet, 18k Rose Gold','Chaumet','Bee My Love','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','chaumet-chaumet-bee-my-love-ring-18k-white-gold-with-diamonds','Chaumet Bee My Love Ring, 18k White Gold with Diamonds','Chaumet','Bee My Love','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','chaumet-chaumet-bee-my-love-pendant-18k-yellow-gold','Chaumet Bee My Love Pendant, 18k Yellow Gold','Chaumet','Bee My Love','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','chaumet-chaumet-liens-vidence-pendant-18k-rose-gold','Chaumet Liens Évidence Pendant, 18k Rose Gold','Chaumet','Liens','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','chaumet-chaumet-liens-vidence-bracelet-18k-white-gold','Chaumet Liens Évidence Bracelet, 18k White Gold','Chaumet','Liens','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','chaumet-chaumet-jos-phine-aigrette-ring-platinum','Chaumet Joséphine Aigrette Ring, Platinum','Chaumet','Joséphine','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','chaumet-chaumet-jos-phine-clat-floral-earrings-18k-white-gold','Chaumet Joséphine Éclat Floral Earrings, 18k White Gold','Chaumet','Joséphine','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','mikimoto-mikimoto-akoya-pearl-strand-necklace','Mikimoto Akoya Pearl Strand Necklace','Mikimoto','Akoya','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','mikimoto-mikimoto-akoya-pearl-stud-earrings-18k-white-gold','Mikimoto Akoya Pearl Stud Earrings, 18k White Gold','Mikimoto','Akoya','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','mikimoto-mikimoto-akoya-pearl-bracelet-18k-yellow-gold','Mikimoto Akoya Pearl Bracelet, 18k Yellow Gold','Mikimoto','Akoya','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','mikimoto-mikimoto-akoya-pearl-pendant-18k-white-gold','Mikimoto Akoya Pearl Pendant, 18k White Gold','Mikimoto','Akoya','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','mikimoto-mikimoto-south-sea-pearl-pendant-18k-white-gold','Mikimoto South Sea Pearl Pendant, 18k White Gold','Mikimoto','South Sea','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','mikimoto-mikimoto-south-sea-pearl-strand-necklace','Mikimoto South Sea Pearl Strand Necklace','Mikimoto','South Sea','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','mikimoto-mikimoto-black-south-sea-pearl-earrings-18k-white-gold','Mikimoto Black South Sea Pearl Earrings, 18k White Gold','Mikimoto','Black South Sea','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','buccellati-buccellati-macri-classica-bracelet-18k-yellow-gold','Buccellati Macri Classica Bracelet, 18k Yellow Gold','Buccellati','Macri','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','buccellati-buccellati-macri-classica-ring-18k-white-gold','Buccellati Macri Classica Ring, 18k White Gold','Buccellati','Macri','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','buccellati-buccellati-macri-eternelle-bangle-18k-yellow-gold','Buccellati Macri Eternelle Bangle, 18k Yellow Gold','Buccellati','Macri','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','buccellati-buccellati-opera-tulle-pendant-18k-yellow-gold','Buccellati Opera Tulle Pendant, 18k Yellow Gold','Buccellati','Opera','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','buccellati-buccellati-opera-tulle-ring-18k-white-gold','Buccellati Opera Tulle Ring, 18k White Gold','Buccellati','Opera','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','buccellati-buccellati-blossoms-ring-sterling-silver','Buccellati Blossoms Ring, Sterling Silver','Buccellati','Blossoms','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','buccellati-buccellati-rombi-cuff-bracelet-18k-yellow-gold','Buccellati Rombi Cuff Bracelet, 18k Yellow Gold','Buccellati','Rombi','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','pomellato-pomellato-nudo-ring-18k-rose-gold-with-blue-topaz','Pomellato Nudo Ring, 18k Rose Gold with Blue Topaz','Pomellato','Nudo','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','pomellato-pomellato-nudo-pendant-18k-white-gold','Pomellato Nudo Pendant, 18k White Gold','Pomellato','Nudo','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','pomellato-pomellato-nudo-earrings-18k-rose-gold-with-amethyst','Pomellato Nudo Earrings, 18k Rose Gold with Amethyst','Pomellato','Nudo','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','pomellato-pomellato-iconica-bracelet-18k-rose-gold','Pomellato Iconica Bracelet, 18k Rose Gold','Pomellato','Iconica','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','pomellato-pomellato-iconica-ring-18k-rose-gold','Pomellato Iconica Ring, 18k Rose Gold','Pomellato','Iconica','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','pomellato-pomellato-sabbia-ring-18k-rose-gold-with-diamonds','Pomellato Sabbia Ring, 18k Rose Gold with Diamonds','Pomellato','Sabbia','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','piaget-piaget-possession-ring-18k-rose-gold','Piaget Possession Ring, 18k Rose Gold','Piaget','Possession','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','piaget-piaget-possession-pendant-18k-white-gold-with-diamonds','Piaget Possession Pendant, 18k White Gold with Diamonds','Piaget','Possession','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','piaget-piaget-possession-bangle-18k-rose-gold','Piaget Possession Bangle, 18k Rose Gold','Piaget','Possession','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','piaget-piaget-rose-pendant-18k-rose-gold','Piaget Rose Pendant, 18k Rose Gold','Piaget','Rose','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','piaget-piaget-rose-ring-18k-white-gold','Piaget Rose Ring, 18k White Gold','Piaget','Rose','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','piaget-piaget-limelight-gala-necklace-18k-rose-gold','Piaget Limelight Gala Necklace, 18k Rose Gold','Piaget','Limelight','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','chopard-chopard-happy-diamonds-pendant-18k-white-gold','Chopard Happy Diamonds Pendant, 18k White Gold','Chopard','Happy Diamonds','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','chopard-chopard-happy-diamonds-icons-ring-18k-rose-gold','Chopard Happy Diamonds Icons Ring, 18k Rose Gold','Chopard','Happy Diamonds','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','chopard-chopard-happy-hearts-bracelet-18k-rose-gold','Chopard Happy Hearts Bracelet, 18k Rose Gold','Chopard','Happy Hearts','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','chopard-chopard-happy-hearts-necklace-18k-white-gold','Chopard Happy Hearts Necklace, 18k White Gold','Chopard','Happy Hearts','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','chopard-chopard-ice-cube-ring-18k-white-gold','Chopard Ice Cube Ring, 18k White Gold','Chopard','Ice Cube','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','chopard-chopard-ice-cube-bracelet-18k-rose-gold','Chopard Ice Cube Bracelet, 18k Rose Gold','Chopard','Ice Cube','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','chanel-chanel-coco-crush-ring-18k-beige-gold','Chanel Coco Crush Ring, 18k Beige Gold','Chanel','Coco Crush','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','chanel-chanel-coco-crush-ring-18k-white-gold-with-diamonds','Chanel Coco Crush Ring, 18k White Gold with Diamonds','Chanel','Coco Crush','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','chanel-chanel-coco-crush-cuff-18k-beige-gold','Chanel Coco Crush Cuff, 18k Beige Gold','Chanel','Coco Crush','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','chanel-chanel-coco-crush-earrings-18k-yellow-gold','Chanel Coco Crush Earrings, 18k Yellow Gold','Chanel','Coco Crush','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','chanel-chanel-cam-lia-ring-18k-white-gold','Chanel Camélia Ring, 18k White Gold','Chanel','Camélia','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','chanel-chanel-extrait-de-cam-lia-bracelet-18k-beige-gold','Chanel Extrait de Camélia Bracelet, 18k Beige Gold','Chanel','Camélia','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','chanel-chanel-ultra-ring-18k-white-gold-with-ceramic','Chanel Ultra Ring, 18k White Gold with Ceramic','Chanel','Ultra','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','chanel-chanel-com-te-necklace-18k-white-gold','Chanel Comète Necklace, 18k White Gold','Chanel','Comète','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','dior-dior-rose-des-vents-necklace-18k-yellow-gold','Dior Rose des Vents Necklace, 18k Yellow Gold','Dior','Rose des Vents','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','dior-dior-rose-des-vents-bracelet-18k-rose-gold','Dior Rose des Vents Bracelet, 18k Rose Gold','Dior','Rose des Vents','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','dior-dior-rose-des-vents-ring-18k-yellow-gold','Dior Rose des Vents Ring, 18k Yellow Gold','Dior','Rose des Vents','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','dior-dior-bois-de-rose-ring-18k-rose-gold','Dior Bois de Rose Ring, 18k Rose Gold','Dior','Bois de Rose','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','dior-dior-bois-de-rose-earrings-18k-yellow-gold','Dior Bois de Rose Earrings, 18k Yellow Gold','Dior','Bois de Rose','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','dior-dior-rose-c-leste-pendant-18k-yellow-gold','Dior Rose Céleste Pendant, 18k Yellow Gold','Dior','Rose Céleste','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','dior-dior-gem-dior-ring-18k-yellow-gold','Dior Gem Dior Ring, 18k Yellow Gold','Dior','Gem Dior','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','herm-s-herm-s-cha-ne-dancre-bracelet-sterling-silver','Hermès Chaîne d''Ancre Bracelet, Sterling Silver','Hermès','Chaîne d''Ancre','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','herm-s-herm-s-cha-ne-dancre-necklace-18k-rose-gold','Hermès Chaîne d''Ancre Necklace, 18k Rose Gold','Hermès','Chaîne d''Ancre','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','herm-s-herm-s-cha-ne-dancre-punk-bracelet-sterling-silver','Hermès Chaîne d''Ancre Punk Bracelet, Sterling Silver','Hermès','Chaîne d''Ancre','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','herm-s-herm-s-clic-h-bracelet-palladium-plated','Hermès Clic H Bracelet, Palladium Plated','Hermès','Clic H','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','herm-s-herm-s-clic-clac-h-bracelet-gold-plated','Hermès Clic Clac H Bracelet, Gold Plated','Hermès','Clic H','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','herm-s-herm-s-kelly-pendant-18k-rose-gold','Hermès Kelly Pendant, 18k Rose Gold','Hermès','Kelly','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','herm-s-herm-s-collier-de-chien-bracelet-sterling-silver','Hermès Collier de Chien Bracelet, Sterling Silver','Hermès','Collier de Chien','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','herm-s-herm-s-finesse-ring-18k-white-gold','Hermès Finesse Ring, 18k White Gold','Hermès','Finesse','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','louis-vuitton-louis-vuitton-empreinte-bangle-18k-yellow-gold','Louis Vuitton Empreinte Bangle, 18k Yellow Gold','Louis Vuitton','Empreinte','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','louis-vuitton-louis-vuitton-empreinte-ring-18k-rose-gold','Louis Vuitton Empreinte Ring, 18k Rose Gold','Louis Vuitton','Empreinte','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','louis-vuitton-louis-vuitton-empreinte-necklace-18k-white-gold','Louis Vuitton Empreinte Necklace, 18k White Gold','Louis Vuitton','Empreinte','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','louis-vuitton-louis-vuitton-idylle-blossom-pendant-18k-yellow-gold','Louis Vuitton Idylle Blossom Pendant, 18k Yellow Gold','Louis Vuitton','Idylle Blossom','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','louis-vuitton-louis-vuitton-color-blossom-bb-pendant-18k-rose-gold','Louis Vuitton Color Blossom BB Pendant, 18k Rose Gold','Louis Vuitton','Color Blossom','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','louis-vuitton-louis-vuitton-lv-volt-curb-chain-bracelet-18k-yellow-gold','Louis Vuitton LV Volt Curb Chain Bracelet, 18k Yellow Gold','Louis Vuitton','LV Volt','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','louis-vuitton-louis-vuitton-lv-volt-one-ring-18k-white-gold','Louis Vuitton LV Volt One Ring, 18k White Gold','Louis Vuitton','LV Volt','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','gucci-gucci-link-to-love-ring-18k-yellow-gold','Gucci Link to Love Ring, 18k Yellow Gold','Gucci','Link to Love','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','gucci-gucci-link-to-love-bracelet-18k-yellow-gold','Gucci Link to Love Bracelet, 18k Yellow Gold','Gucci','Link to Love','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','gucci-gucci-ouroboros-ring-18k-yellow-gold','Gucci Ouroboros Ring, 18k Yellow Gold','Gucci','Ouroboros','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','gucci-gucci-icon-ring-18k-white-gold','Gucci Icon Ring, 18k White Gold','Gucci','Icon','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','gucci-gucci-flora-necklace-18k-yellow-gold','Gucci Flora Necklace, 18k Yellow Gold','Gucci','Flora','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','tasaki-tasaki-balance-necklace-18k-white-gold-with-pearls','Tasaki Balance Necklace, 18k White Gold with Pearls','Tasaki','Balance','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','tasaki-tasaki-balance-signature-ring-18k-rose-gold','Tasaki Balance Signature Ring, 18k Rose Gold','Tasaki','Balance','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','tasaki-tasaki-danger-plus-bracelet-18k-yellow-gold','Tasaki Danger Plus Bracelet, 18k Yellow Gold','Tasaki','Danger','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','tasaki-tasaki-kaleidoscope-earrings-18k-white-gold','Tasaki Kaleidoscope Earrings, 18k White Gold','Tasaki','Kaleidoscope','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','georg-jensen-georg-jensen-moonlight-grapes-bracelet-sterling-silver','Georg Jensen Moonlight Grapes Bracelet, Sterling Silver','Georg Jensen','Moonlight Grapes','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','georg-jensen-georg-jensen-offspring-pendant-sterling-silver','Georg Jensen Offspring Pendant, Sterling Silver','Georg Jensen','Offspring','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','georg-jensen-georg-jensen-daisy-ring-sterling-silver-with-enamel','Georg Jensen Daisy Ring, Sterling Silver with Enamel','Georg Jensen','Daisy','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','damiani-damiani-belle-poque-ring-18k-white-gold','Damiani Belle Époque Ring, 18k White Gold','Damiani','Belle Époque','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','damiani-damiani-d-icon-bracelet-18k-rose-gold','Damiani D.Icon Bracelet, 18k Rose Gold','Damiani','D.Icon','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','vhernier-vhernier-calla-pendant-18k-rose-gold','Vhernier Calla Pendant, 18k Rose Gold','Vhernier','Calla','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','vhernier-vhernier-freccia-bracelet-18k-white-gold','Vhernier Freccia Bracelet, 18k White Gold','Vhernier','Freccia','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','faberg-faberg-heritage-egg-pendant-18k-yellow-gold-with-enamel','Fabergé Heritage Egg Pendant, 18k Yellow Gold with Enamel','Fabergé','Egg','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','faberg-faberg-colours-of-love-ring-18k-rose-gold','Fabergé Colours of Love Ring, 18k Rose Gold','Fabergé','Colours of Love','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','marco-bicego-marco-bicego-jaipur-link-bracelet-18k-yellow-gold','Marco Bicego Jaipur Link Bracelet, 18k Yellow Gold','Marco Bicego','Jaipur','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','marco-bicego-marco-bicego-lunaria-necklace-18k-yellow-gold','Marco Bicego Lunaria Necklace, 18k Yellow Gold','Marco Bicego','Lunaria','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','marco-bicego-marco-bicego-africa-bangle-18k-yellow-gold','Marco Bicego Africa Bangle, 18k Yellow Gold','Marco Bicego','Africa','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','roberto-coin-roberto-coin-symphony-princess-ring-18k-rose-gold','Roberto Coin Symphony Princess Ring, 18k Rose Gold','Roberto Coin','Symphony','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','roberto-coin-roberto-coin-love-in-verona-pendant-18k-yellow-gold','Roberto Coin Love in Verona Pendant, 18k Yellow Gold','Roberto Coin','Love in Verona','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','roberto-coin-roberto-coin-appassionata-bracelet-18k-yellow-gold','Roberto Coin Appassionata Bracelet, 18k Yellow Gold','Roberto Coin','Appassionata','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','foundrae-foundrae-karma-medallion-pendant-18k-yellow-gold','Foundrae Karma Medallion Pendant, 18k Yellow Gold','Foundrae','Medallion','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','foundrae-foundrae-strength-cigar-band-ring-18k-yellow-gold','Foundrae Strength Cigar Band Ring, 18k Yellow Gold','Foundrae','Cigar Band','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','spinelli-kilcollin-spinelli-kilcollin-nova-linked-ring-sterling-silver-and-18k-gold','Spinelli Kilcollin Nova Linked Ring, Sterling Silver and 18k Gold','Spinelli Kilcollin','Linked Ring','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','spinelli-kilcollin-spinelli-kilcollin-vega-linked-ring-18k-yellow-gold','Spinelli Kilcollin Vega Linked Ring, 18k Yellow Gold','Spinelli Kilcollin','Linked Ring','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','anita-ko-anita-ko-hepburn-earrings-18k-rose-gold','Anita Ko Hepburn Earrings, 18k Rose Gold','Anita Ko','Hepburn','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','anita-ko-anita-ko-palm-leaf-ring-18k-yellow-gold','Anita Ko Palm Leaf Ring, 18k Yellow Gold','Anita Ko','Palm Leaf','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','suzanne-kalan-suzanne-kalan-fireworks-eternity-band-18k-rose-gold','Suzanne Kalan Fireworks Eternity Band, 18k Rose Gold','Suzanne Kalan','Fireworks','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','suzanne-kalan-suzanne-kalan-fireworks-pendant-18k-yellow-gold','Suzanne Kalan Fireworks Pendant, 18k Yellow Gold','Suzanne Kalan','Fireworks','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','david-yurman-david-yurman-cable-classic-bracelet-sterling-silver','David Yurman Cable Classic Bracelet, Sterling Silver','David Yurman','Cable','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','david-yurman-david-yurman-cable-collectibles-necklace-18k-yellow-gold','David Yurman Cable Collectibles Necklace, 18k Yellow Gold','David Yurman','Cable','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','david-yurman-david-yurman-cable-cuff-sterling-silver-with-diamonds','David Yurman Cable Cuff, Sterling Silver with Diamonds','David Yurman','Cable','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','dinh-van-dinh-van-menottes-r12-bracelet-18k-yellow-gold','Dinh Van Menottes R12 Bracelet, 18k Yellow Gold','Dinh Van','Menottes','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','dinh-van-dinh-van-le-cube-diamant-pendant-18k-white-gold','Dinh Van Le Cube Diamant Pendant, 18k White Gold','Dinh Van','Le Cube','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','dinh-van-dinh-van-serrure-bracelet-18k-rose-gold','Dinh Van Serrure Bracelet, 18k Rose Gold','Dinh Van','Serrure','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','repossi-repossi-berbere-ear-cuff-18k-rose-gold','Repossi Berbere Ear Cuff, 18k Rose Gold','Repossi','Berbere','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','repossi-repossi-berbere-ring-18k-white-gold','Repossi Berbere Ring, 18k White Gold','Repossi','Berbere','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','fred-paris-fred-paris-force-10-bracelet-18k-yellow-gold','Fred Paris Force 10 Bracelet, 18k Yellow Gold','Fred Paris','Force 10','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','fred-paris-fred-paris-force-10-ring-18k-white-gold','Fred Paris Force 10 Ring, 18k White Gold','Fred Paris','Force 10','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','fred-paris-fred-paris-chance-infinie-ring-18k-white-gold','Fred Paris Chance Infinie Ring, 18k White Gold','Fred Paris','Chance Infinie','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','boodles-boodles-raindance-ring-platinum','Boodles Raindance Ring, Platinum','Boodles','Raindance','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','boodles-boodles-blossom-pendant-18k-rose-gold','Boodles Blossom Pendant, 18k Rose Gold','Boodles','Blossom','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','garrard-garrard-fanfare-symphony-pendant-18k-white-gold','Garrard Fanfare Symphony Pendant, 18k White Gold','Garrard','Fanfare','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','garrard-garrard-wings-classic-ring-18k-rose-gold','Garrard Wings Classic Ring, 18k Rose Gold','Garrard','Wings','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','asprey-asprey-woodland-pendant-18k-yellow-gold','Asprey Woodland Pendant, 18k Yellow Gold','Asprey','Woodland','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','asprey-asprey-chaos-ring-18k-white-gold','Asprey Chaos Ring, 18k White Gold','Asprey','Chaos','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','verdura-verdura-maltese-cross-cuff-18k-yellow-gold-with-enamel','Verdura Maltese Cross Cuff, 18k Yellow Gold with Enamel','Verdura','Maltese Cross','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','seaman-schepps-seaman-schepps-link-bracelet-18k-yellow-gold','Seaman Schepps Link Bracelet, 18k Yellow Gold','Seaman Schepps','Link','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb),
  ('jewellery','ole-lynggaard-ole-lynggaard-lotus-ring-18k-yellow-gold','Ole Lynggaard Lotus Ring, 18k Yellow Gold','Ole Lynggaard','Lotus','seed',false,'{"seed_batch": "jewellery_2026_08_11"}'::jsonb)
ON CONFLICT (category, item_key) DO UPDATE
  SET title = EXCLUDED.title, brand = EXCLUDED.brand, notes = EXCLUDED.notes,
      attributes_json = EXCLUDED.attributes_json, updated_at = now();

-- Read before COMMIT. Expect 317 rows, 41 brands, 6 archived Etoile.
SELECT count(*) AS rows_now, count(DISTINCT brand) AS brands,
       count(*) FILTER (WHERE attributes_json->>'status'='archived') AS archived_etoile
FROM category_items WHERE category='jewellery';

COMMIT;

-- Reversal: check nothing bound to these keys first —
--   SELECT count(*) FROM items WHERE canonical_key IN (
--     SELECT item_key FROM category_items
--     WHERE attributes_json->>'seed_batch'='jewellery_2026_08_11');
-- then DELETE FROM category_items WHERE category='jewellery'
--   AND attributes_json->>'seed_batch'='jewellery_2026_08_11';
