export const featureFlags = {
  darkMode: false,
  FEATURE_HAPTICS_MICRO_ANIMATIONS: true,
  FEATURE_ACCESSIBILITY_ENHANCEMENTS: true,
  FEATURE_DATA_INSIGHTS_ALERTS: true,
  FEATURE_EXPLAINABLE_AI_INTERFACES: true,
  FEATURE_GESTURE_THUMB_NAVIGATION: true,
};
