"""Read docs/schema-lock-matrix.json and produce a "lock readiness" report
under docs/schema-lock-readiness.md.

For each touched table, classify each column as one of:
  - LOCKED       : (FE_W AND BE_W) OR (FE_R AND BE_R) — round-trip evidence
  - WRITE_ONLY   : FE_W + BE_W only (write side complete, read side missing
                   — typically OK for write-only / fire-and-forget paths)
  - READ_ONLY    : FE_R + BE_R only (read complete, never written by FE — OK
                   for derived/compute columns)
  - FE_DRIFT     : FE references column but BE doesn't write/read it OR vice
                   versa — broken contract
  - SCHEMA_ONLY  : column in schema, no code touches at all
  - STRAY        : code references a column that's NOT in the schema (drift)

Also produces a "next-step E2E" suggestion per table:
  - "✅ ready to lock"      = all FE-touched columns are LOCKED + no strays
  - "⚠ partial lock"        = some columns LOCKED, others FE_DRIFT
  - "🔧 needs FE/BE wiring" = columns are READ_ONLY or WRITE_ONLY only
  - "🚨 fix strays first"   = stray refs found
"""
from __future__ import annotations
import json
from pathlib import Path
from collections import Counter

ROOT = Path(__file__).resolve().parent.parent
MATRIX = ROOT / "docs" / "schema-lock-matrix.json"
SCHEMA = ROOT / "scripts" / "schema.lock.json"
OUT = ROOT / "docs" / "schema-lock-readiness.md"

def classify(col_state: dict, table_state: dict) -> str:
    """Classify a single column.

    table_state has the per-table aggregate counters used to detect when
    a table is FE-direct-only (RLS-protected) vs has BE handlers that
    the FE inconsistently bypasses.
    """
    fr, fw, br, bw = col_state["fe_r"], col_state["fe_w"], col_state["be_r"], col_state["be_w"]
    has_any_be_read = table_state["be_read_total"] > 0
    has_any_be_write = table_state["be_write_total"] > 0

    if (fw and bw) or (fr and br):
        return "LOCKED"

    # If FE writes a column and the BE has NO writes on this table at all,
    # this is RLS-direct write — intentional, the table is protected by
    # row-level security and the FE writes through Supabase REST. Same for
    # reads. Not a bug.
    if fw and not bw and not has_any_be_write:
        return "RLS_DIRECT_WRITE"
    if fr and not br and not has_any_be_read:
        return "RLS_DIRECT_READ"

    # If the BE DOES write/read this table but not this specific column,
    # it's a real contract gap — FE references something the BE handler
    # doesn't acknowledge.
    if fw and not bw and has_any_be_write:
        return "FE_DRIFT"
    if fr and not br and has_any_be_read:
        return "FE_DRIFT"

    if bw and not fw:
        return "WRITE_ONLY"
    if br and not fr:
        return "READ_ONLY"
    return "SCHEMA_ONLY"

def status_emoji(stats: dict, has_strays: bool) -> str:
    if has_strays:
        return "🚨 fix strays first"
    if stats["FE_DRIFT"] > 0:
        return "⚠️ partial lock"
    rls_direct = stats["RLS_DIRECT_WRITE"] + stats["RLS_DIRECT_READ"]
    if rls_direct > 0 and stats["LOCKED"] == 0:
        return "🔓 RLS-direct (intentional, no BE handler)"
    if stats["LOCKED"] == 0 and (stats["READ_ONLY"] + stats["WRITE_ONLY"]) > 0:
        return "🔧 needs round-trip wiring"
    if stats["LOCKED"] > 0 and stats["FE_DRIFT"] == 0:
        return "✅ ready to lock"
    return "· no FE-side activity"

def main():
    matrix = json.loads(MATRIX.read_text())
    schema = json.loads(SCHEMA.read_text())

    lines = [
        "# Schema lock — readiness report",
        "",
        "Per-table summary derived from `docs/schema-lock-matrix.json`. Tells you",
        "which tables are ready to *lock* (all FE↔BE touched columns are round-",
        "trip verified) vs which need wiring or have drift.",
        "",
        "Generated by `scripts/lock_readiness_audit.py`.",
        "",
        "## Legend",
        "",
        "Per column:",
        "- **LOCKED**: FE_W+BE_W (write round-trip) OR FE_R+BE_R (read round-trip)",
        "- **WRITE_ONLY**: server writes (e.g. computed columns) but FE never sends",
        "- **READ_ONLY**: server reads but FE never exposes (server-side only)",
        "- **FE_DRIFT**: FE touches a column but the corresponding BE side doesn't — broken contract",
        "- **STRAY**: code references a column that's not in the schema lock",
        "",
        "Per table:",
        "- ✅ **ready to lock** — every FE-touched column is LOCKED, no strays",
        "- ⚠️ **partial lock** — some FE_DRIFT columns exist (real bugs)",
        "- 🔧 **needs round-trip wiring** — only one direction wired",
        "- 🚨 **fix strays first** — code references columns not in schema",
        "",
    ]

    # Sort tables by status priority: strays > drift > partial > ready
    table_summaries = []
    for table_name in sorted(matrix["tables"].keys()):
        t = matrix["tables"][table_name]
        cols = t["columns"]
        # Aggregate: does BE touch this table at all?
        table_state = {
            "be_read_total": sum(1 for s in cols.values() if s["be_r"]),
            "be_write_total": sum(1 for s in cols.values() if s["be_w"]),
        }
        stats = Counter(classify(s, table_state) for s in cols.values())
        strays = t["stray"]
        status = status_emoji(stats, bool(strays))
        n_total = len(cols)
        n_locked = stats["LOCKED"]
        n_drift = stats["FE_DRIFT"]
        table_summaries.append((status, table_name, stats, strays, n_total, n_locked, n_drift, t))

    # Bucket by status emoji
    BUCKETS = [
        ("🚨 fix strays first", "Tables with stray refs (code references columns not in schema)"),
        ("⚠️ partial lock", "Tables with FE_DRIFT — FE column referenced but the SAME table has BE handlers that ignore it (likely real bug)"),
        ("🔧 needs round-trip wiring", "Tables wired in only one direction (server-only or FE-only with no opposite link)"),
        ("🔓 RLS-direct (intentional, no BE handler)", "Tables FE accesses directly via Supabase REST + RLS — no BE handler exists for the table at all. Intentional pattern."),
        ("✅ ready to lock", "Tables fully verified, ready to lock"),
        ("· no FE-side activity", "Tables touched only by server (admin / worker / internal)"),
    ]

    # Allowlisted strays — gated/dormant references kept out of the
    # "fix strays first" bucket per scripts/stray_drift_allowlist.txt.
    # Surfaced separately so they don't disappear from sight.
    allow_rows = []
    for table_name in sorted(matrix["tables"].keys()):
        t = matrix["tables"][table_name]
        allow = t.get("stray_allowlisted") or []
        if allow:
            allow_rows.append((table_name, allow))
    if allow_rows:
        lines.append("## 📎 allowlisted strays — gated/dormant")
        lines.append("")
        lines.append(
            "Stray refs intentionally kept out of the fix-list because the call "
            "chain proves they can't fire at runtime. See `scripts/stray_drift_allowlist.txt` "
            "for the per-entry trace. Removing an entry from the allowlist requires "
            "either fixing the underlying code or deleting the dead reference."
        )
        lines.append("")
        lines.append("| table | columns |")
        lines.append("|---|---|")
        for table_name, cols in allow_rows:
            lines.append(f"| `{table_name}` | `{', '.join(cols)}` |")
        lines.append("")

    for status_label, blurb in BUCKETS:
        bucket = [s for s in table_summaries if s[0] == status_label]
        if not bucket:
            continue
        lines.append(f"## {status_label} — {len(bucket)} tables")
        lines.append("")
        lines.append(blurb)
        lines.append("")
        lines.append("| table | total cols | LOCKED | FE_DRIFT | strays | next E2E step |")
        lines.append("|---|---|---|---|---|---|")
        for status, table_name, stats, strays, n_total, n_locked, n_drift, t in sorted(bucket, key=lambda x: -x[6]):
            stray_str = f"`{', '.join(strays[:3])}{'...' if len(strays) > 3 else ''}`" if strays else "—"
            # Suggest the next E2E step for this table
            cols = t["columns"]
            table_state = {
                "be_read_total": sum(1 for s in cols.values() if s["be_r"]),
                "be_write_total": sum(1 for s in cols.values() if s["be_w"]),
            }
            drift_cols = [c for c, s in cols.items() if classify(s, table_state) == "FE_DRIFT"]
            if strays:
                step = f"Fix strays: {strays[:3]} (rename in code OR add column)"
            elif drift_cols:
                missing_writes = [c for c in drift_cols if cols[c]["fe_w"] and not cols[c]["be_w"]]
                missing_reads = [c for c in drift_cols if cols[c]["fe_r"] and not cols[c]["be_r"]]
                parts = []
                if missing_writes: parts.append(f"BE write-handler for: {missing_writes[:3]}")
                if missing_reads:  parts.append(f"BE read-handler for: {missing_reads[:3]}")
                step = "; ".join(parts) or "review FE_DRIFT cols"
            elif stats["LOCKED"] == 0:
                # Round-trip needed
                ro = [c for c, s in cols.items() if classify(s, table_state) == "READ_ONLY"]
                wo = [c for c, s in cols.items() if classify(s, table_state) == "WRITE_ONLY"]
                parts = []
                if ro: parts.append(f"FE read needed for: {ro[:3]}")
                if wo: parts.append(f"FE write needed for: {wo[:3]}")
                step = "; ".join(parts) or "consider locking"
            else:
                step = "lock candidate"
            lines.append(f"| `{table_name}` | {n_total} | {n_locked} | {n_drift} | {stray_str} | {step} |")
        lines.append("")

    OUT.write_text("\n".join(lines) + "\n")
    print(f"Wrote {OUT}")
    # Quick stdout summary
    by_status = Counter(s[0] for s in table_summaries)
    for st, n in by_status.most_common():
        print(f"  {st}: {n}")

if __name__ == "__main__":
    main()
