-- 2026-09-22: class AC sweep — 121 SECURITY DEFINER functions that no client
-- calls were executable by anyone holding the anon key.
--
-- Postgres grants EXECUTE on every new function to PUBLIC (proacl `=X/owner`),
-- and anon/authenticated inherit it. DEFINER functions run as `postgres` and
-- bypass RLS, and many take the acting user's id as a PARAMETER — e.g.
-- rpc_send_message_v1(thread, sender, body) — so over PostgREST anyone could
-- act as any member. The server calls these as `postgres` (asyncpg), which
-- owns them and keeps EXECUTE.
--
-- HOW THE LIST WAS BUILT (mechanically, 2026-09-22, not by judgment):
-- all 144 DEFINER functions in public that anon could execute, classified by
-- what needs the CALLER to hold EXECUTE. Kept (23), and why:
--   CLIENT (16)     named in a `.rpc('…')` in src/, app/, supabase/functions/
--                   or collectai-admin/src/ — the current app calls them.
--                   No RPC name has left the app code since 2026-05-01
--                   (git log -p), so older builds call nothing extra.
--   POLICY (1)      is_chat_thread_member — evaluated inside RLS as the caller
--   VIEW (2)        item_value_v1, rpc_user_relevant_events_v1 — used in views
--   INVOKER_FN (1)  predict_and_insert_v2 — called by an INVOKER function
--   TRIGGER (3)     not callable over PostgREST; EXECUTE is not checked at fire
-- Revoked (121): everything else. Checked for each: no explicit grantee
-- besides anon/authenticated/service_role/postgres; no auth-hook signature;
-- the 4 cron jobs that call some of them run as postgres (the owner).
-- Server pipelines call upsert_market_hits_batch over PostgREST with the
-- SERVICE key — service_role is granted below.
--
-- Revoke, not DROP: fully reversible with GRANT EXECUTE … TO authenticated.
--
-- FALSIFIER:
--   SELECT count(*) FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace
--   AND n.nspname='public' WHERE p.prosecdef
--   AND has_function_privilege('anon', p.oid, 'EXECUTE');
--   -> 23 after this file (was 150 before 20260922b, 144 after it).

REVOKE EXECUTE ON FUNCTION
  public._ingest_one_hit(rec jsonb),
  public._job_log_finish(p_id bigint, p_ok boolean, p_info jsonb),
  public._job_log_start(p_job text, p_info jsonb),
  public.api_category_item_status_v1_for_user(p_user_id uuid),
  public.enqueue_price_outliers(),
  public.predict_and_insert(p_name text, p_image_url text),
  public.require_service_role_v1(),
  public.resolve_item_ref_from_nk(p_nk text),
  public.rpc_add_missing_to_wishlist_v1(p_checklist_item_id uuid),
  public.rpc_admin_read_user_items_v1(p_user_id uuid),
  public.rpc_alert_attempt_finish(p_id bigint, p_ok boolean, p_error text, p_backoff_seconds integer),
  public.rpc_alerts_mark_delivered(p_ids bigint[]),
  public.rpc_anonymize_my_account_v1(),
  public.rpc_anonymize_my_account_v2(),
  public.rpc_api_integrity_check_v1(),
  public.rpc_api_key_check(p_key_plain text),
  public.rpc_api_rate_allow(p_key_plain text),
  public.rpc_apply_item_extractions_dev_v1(p_user_id uuid, p_item_id uuid, p_high_threshold numeric, p_medium_threshold numeric),
  public.rpc_apply_item_extractions_v1(p_item_id uuid, p_high_threshold numeric, p_medium_threshold numeric),
  public.rpc_category_item_status_user_v1(p_user_id uuid),
  public.rpc_claim_task_v1(p_task_types text[]),
  public.rpc_complete_task_v1(p_task_id uuid, p_result jsonb),
  public.rpc_confirm_item_identity_v1(p_item_id uuid),
  public.rpc_confirm_item_price_dev_v1(p_user_id uuid, p_item_id uuid, p_price_eur numeric),
  public.rpc_confirm_item_price_v1(p_item_id uuid, p_price_eur numeric),
  public.rpc_confirm_item_suggestion_dev_v1(p_user_id uuid, p_item_id uuid, p_field text),
  public.rpc_confirm_item_suggestion_v1(p_item_id uuid, p_field text),
  public.rpc_create_private_thread_v1(),
  public.rpc_create_project_v1(p_title text, p_status text),
  public.rpc_enqueue_push_v1(p_title text, p_body text, p_data jsonb, p_dedupe_key text, p_notification_id uuid),
  public.rpc_enqueue_task_v1(p_task_type text, p_payload jsonb, p_priority integer, p_scheduled_for timestamp with time zone),
  public.rpc_ensure_thread_reads_v1(),
  public.rpc_execute_fixit_action_v1(p_action_id text, p_item_id uuid),
  public.rpc_export_my_data_v1(),
  public.rpc_export_my_items_csv_v1(),
  public.rpc_fail_task_v1(p_task_id uuid, p_error text),
  public.rpc_feedback_log_v1(p_user_id uuid, p_event_type text, p_payload jsonb, p_item_id uuid, p_item_ref text, p_category_slug text, p_canonical_key text),
  public.rpc_follow_events_v1(p_canonical_key text, p_category text, p_enabled boolean),
  public.rpc_get_calendar_agenda_dev_v1(p_user_id uuid, p_days integer, p_limit integer),
  public.rpc_get_calendar_agenda_v1(p_days integer, p_limit integer),
  public.rpc_get_calendar_agenda_with_watch_dev_v1(p_user_id uuid, p_days integer, p_limit integer),
  public.rpc_get_calendar_agenda_with_watch_merged_dev_v1(p_user_id uuid, p_days integer, p_limit integer),
  public.rpc_get_calendar_agenda_with_watch_v1(p_days integer, p_limit integer),
  public.rpc_get_calendar_feed_dev_v1(p_user_id uuid, p_date_from timestamp with time zone, p_date_to timestamp with time zone, p_limit integer),
  public.rpc_get_chat_inbox_v1(p_limit integer),
  public.rpc_get_chat_thread_v1(p_thread_id uuid, p_limit integer),
  public.rpc_get_event_detail_dev_v1(p_user_id uuid, p_event_id uuid),
  public.rpc_get_event_detail_v1(p_event_id uuid),
  public.rpc_get_item_detail(p_item_ref uuid),
  public.rpc_get_or_create_wishlist(),
  public.rpc_get_provenance_audit(p_limit integer),
  public.rpc_get_quickscan_draft_from_event_dev_v1(p_user_id uuid, p_event_id uuid),
  public.rpc_get_quickscan_prefill_dev_v1(p_user_id uuid, p_item_id uuid),
  public.rpc_get_quickscan_prefill_dev_v2(p_user_id uuid, p_item_id uuid),
  public.rpc_get_quickscan_prefill_v1(p_item_id uuid),
  public.rpc_get_quickscan_prefill_v2_dev_v1(p_user_id uuid, p_item_id uuid),
  public.rpc_get_quickscan_prefill_v3_dev_v1(p_user_id uuid, p_item_id uuid),
  public.rpc_get_quickscan_ui_state_dev_v1(p_user_id uuid, p_item_id uuid),
  public.rpc_get_quickscan_ui_state_dev_v2(p_user_id uuid, p_item_id uuid),
  public.rpc_get_quickscan_ui_state_v2(p_item_id uuid),
  public.rpc_get_quickscan_ui_state_v2_badges(p_item_id uuid),
  public.rpc_get_quickscan_ui_state_v2_polished(p_item_id uuid),
  public.rpc_get_quickscan_v2_dev_v1(p_user_id uuid, p_item_id uuid),
  public.rpc_get_task_status_v1(p_task_id uuid),
  public.rpc_get_user_activity_v1(p_user_id uuid, p_limit integer, p_offset integer),
  public.rpc_home_feed(p_user_id uuid, p_take integer),
  public.rpc_ingest_event_dev_v1(p_source text, p_event_type text, p_title text, p_starts_at timestamp with time zone, p_source_event_id text, p_description text, p_category text, p_canonical_key text, p_url text, p_city text, p_country text, p_venue_name text, p_latitude numeric, p_longitude numeric, p_ends_at timestamp with time zone, p_is_cancelled boolean),
  public.rpc_ingest_event_v1(p_source text, p_event_type text, p_title text, p_starts_at timestamp with time zone, p_source_event_id text, p_description text, p_category text, p_canonical_key text, p_url text, p_city text, p_country text, p_venue_name text, p_latitude numeric, p_longitude numeric, p_ends_at timestamp with time zone, p_is_cancelled boolean),
  public.rpc_ingest_events_batch_dev_v1(p_payload jsonb),
  public.rpc_ingest_events_batch_gated_dev_v1(p_user_id uuid, p_payload jsonb, p_mode text),
  public.rpc_ingest_market_hits(p_hits jsonb),
  public.rpc_item_timeseries_90d(p_item_ref uuid),
  public.rpc_join_category_chat_v1(p_category text),
  public.rpc_lens_list(p_after_item_ref uuid, p_brand text, p_set_name text, p_category text, p_search text, p_sort text, p_limit integer),
  public.rpc_lens_list_v2(p_after uuid, p_brand text, p_set_name text, p_category text, p_q text, p_sort text, p_limit integer),
  public.rpc_list_personalized_events_v1(p_user_id text, p_category_id text, p_include_past boolean),
  public.rpc_lock_item_identity_v1(p_item_id uuid),
  public.rpc_log_activity_v1(p_activity_type text, p_title text, p_description text, p_metadata jsonb, p_is_public boolean),
  public.rpc_portfolio_snapshot_all_users_v1(p_as_of_date date),
  public.rpc_portfolio_snapshot_upsert_v1(p_user_id uuid, p_as_of_date date),
  public.rpc_prune_maintenance(),
  public.rpc_quickscan_apply_extractions_dev_v1(p_user_id uuid, p_item_id uuid, p_min_conf_confirm numeric, p_min_conf_suggest numeric),
  public.rpc_quickscan_apply_extractions_v1(p_item_id uuid, p_min_conf_confirm numeric, p_min_conf_suggest numeric),
  public.rpc_quickscan_autofill_v1(p_item_id uuid),
  public.rpc_quickscan_confirm_all_suggestions_dev_v1(p_user_id uuid, p_item_id uuid),
  public.rpc_quickscan_confirm_all_suggestions_v1(p_item_id uuid),
  public.rpc_quickscan_confirm_price_dev_v1(p_user_id uuid, p_item_id uuid, p_price_eur numeric),
  public.rpc_quickscan_confirm_price_v1(p_item_id uuid, p_price_eur numeric),
  public.rpc_quickscan_confirm_suggestions_and_state_v1(p_item_id uuid),
  public.rpc_quickscan_create_draft_v1(p_category text, p_title_hint text, p_image_uri text, p_source text),
  public.rpc_quickscan_finalize_draft_to_item_v1(p_draft_id uuid, p_category text, p_canonical_key text, p_title text),
  public.rpc_quickscan_get_ui_state_v1(p_item_id uuid),
  public.rpc_quickscan_one_tap_dev_v1(p_user_id uuid, p_category text, p_canonical_key text, p_title_hint text, p_image_uri text, p_price_eur numeric, p_auto_confirm_suggestions boolean),
  public.rpc_quickscan_one_tap_v1(p_category text, p_canonical_key text, p_title_hint text, p_image_uri text, p_price_eur numeric, p_auto_confirm_suggestions boolean),
  public.rpc_quickscan_one_tap_v2(p_category text, p_canonical_key text, p_title_hint text, p_image_uri text, p_price_eur numeric, p_auto_confirm_suggestions boolean),
  public.rpc_quickscan_seed_extraction_from_title_dev_v1(p_user_id uuid, p_item_id uuid),
  public.rpc_quickscan_seed_extraction_from_title_v1(p_item_id uuid),
  public.rpc_register_push_device_v1(p_token text, p_platform text, p_device_label text, p_app_version text, p_provider text),
  public.rpc_run_daily_guidance_v1(p_user_id uuid),
  public.rpc_search_items(p_q text, p_limit integer),
  public.rpc_send_message_v1(p_thread_id uuid, p_user_id uuid, p_body text),
  public.rpc_set_presence_v1(p_status text, p_thread_id uuid, p_meta jsonb),
  public.rpc_submit_purchase_price_v1(p_item_ref text, p_price_eur numeric, p_condition_grade text),
  public.rpc_toggle_reaction_v1(p_message_id uuid, p_emoji text),
  public.rpc_top_movers_cached(p_limit integer, p_sort text),
  public.rpc_training_items_upsert_v1(p_category_slug text, p_canonical_key text, p_display_name text, p_attributes jsonb, p_anchor_price_eur numeric, p_anchor_price_date date, p_anchor_source text, p_source_url text, p_confidence_hint text, p_is_active boolean),
  public.rpc_unfollow_events_v1(p_canonical_key text, p_category text),
  public.rpc_unmark_category_item_owned_v1(p_category_item_id uuid),
  public.rpc_upsert_item_metadata_by_nk(p_nk text, p_category text, p_brand text, p_variant text, p_set_name text, p_language text, p_rarity text, p_release_year integer, p_notes text),
  public.rpc_watch_event_dev_v1(p_user_id uuid, p_event_id uuid, p_target_price_eur numeric, p_notes text),
  public.rpc_watch_event_v1(p_event_id uuid, p_target_price_eur numeric, p_notes text),
  public.rpc_watchlist_add_by_nk(p_user_id uuid, p_nk text),
  public.rpc_watchlist_add_by_ref(p_user_id uuid, p_item_ref uuid),
  public.rpc_watchlist_remove(p_user_id uuid, p_item_ref uuid),
  public.rpc_wishlist_disable_v1(p_canonical_key text),
  public.rpc_wishlist_upsert_v1(p_canonical_key text, p_category text, p_target_price_eur numeric, p_notes text, p_enabled boolean),
  public.secure_partition_rls(),
  public.sync_metadata_ai_v1(p_item_id uuid, p_attrs jsonb, p_ai_source text, p_ai_confidence numeric, p_force boolean),
  public.update_watchlist_valuation_v1(),
  public.upsert_item_metadata_by_ref(p_item_ref uuid, p_attrs jsonb),
  public.upsert_market_hits_batch(rows jsonb)
FROM PUBLIC, anon, authenticated;

GRANT EXECUTE ON FUNCTION
  public._ingest_one_hit(rec jsonb),
  public._job_log_finish(p_id bigint, p_ok boolean, p_info jsonb),
  public._job_log_start(p_job text, p_info jsonb),
  public.api_category_item_status_v1_for_user(p_user_id uuid),
  public.enqueue_price_outliers(),
  public.predict_and_insert(p_name text, p_image_url text),
  public.require_service_role_v1(),
  public.resolve_item_ref_from_nk(p_nk text),
  public.rpc_add_missing_to_wishlist_v1(p_checklist_item_id uuid),
  public.rpc_admin_read_user_items_v1(p_user_id uuid),
  public.rpc_alert_attempt_finish(p_id bigint, p_ok boolean, p_error text, p_backoff_seconds integer),
  public.rpc_alerts_mark_delivered(p_ids bigint[]),
  public.rpc_anonymize_my_account_v1(),
  public.rpc_anonymize_my_account_v2(),
  public.rpc_api_integrity_check_v1(),
  public.rpc_api_key_check(p_key_plain text),
  public.rpc_api_rate_allow(p_key_plain text),
  public.rpc_apply_item_extractions_dev_v1(p_user_id uuid, p_item_id uuid, p_high_threshold numeric, p_medium_threshold numeric),
  public.rpc_apply_item_extractions_v1(p_item_id uuid, p_high_threshold numeric, p_medium_threshold numeric),
  public.rpc_category_item_status_user_v1(p_user_id uuid),
  public.rpc_claim_task_v1(p_task_types text[]),
  public.rpc_complete_task_v1(p_task_id uuid, p_result jsonb),
  public.rpc_confirm_item_identity_v1(p_item_id uuid),
  public.rpc_confirm_item_price_dev_v1(p_user_id uuid, p_item_id uuid, p_price_eur numeric),
  public.rpc_confirm_item_price_v1(p_item_id uuid, p_price_eur numeric),
  public.rpc_confirm_item_suggestion_dev_v1(p_user_id uuid, p_item_id uuid, p_field text),
  public.rpc_confirm_item_suggestion_v1(p_item_id uuid, p_field text),
  public.rpc_create_private_thread_v1(),
  public.rpc_create_project_v1(p_title text, p_status text),
  public.rpc_enqueue_push_v1(p_title text, p_body text, p_data jsonb, p_dedupe_key text, p_notification_id uuid),
  public.rpc_enqueue_task_v1(p_task_type text, p_payload jsonb, p_priority integer, p_scheduled_for timestamp with time zone),
  public.rpc_ensure_thread_reads_v1(),
  public.rpc_execute_fixit_action_v1(p_action_id text, p_item_id uuid),
  public.rpc_export_my_data_v1(),
  public.rpc_export_my_items_csv_v1(),
  public.rpc_fail_task_v1(p_task_id uuid, p_error text),
  public.rpc_feedback_log_v1(p_user_id uuid, p_event_type text, p_payload jsonb, p_item_id uuid, p_item_ref text, p_category_slug text, p_canonical_key text),
  public.rpc_follow_events_v1(p_canonical_key text, p_category text, p_enabled boolean),
  public.rpc_get_calendar_agenda_dev_v1(p_user_id uuid, p_days integer, p_limit integer),
  public.rpc_get_calendar_agenda_v1(p_days integer, p_limit integer),
  public.rpc_get_calendar_agenda_with_watch_dev_v1(p_user_id uuid, p_days integer, p_limit integer),
  public.rpc_get_calendar_agenda_with_watch_merged_dev_v1(p_user_id uuid, p_days integer, p_limit integer),
  public.rpc_get_calendar_agenda_with_watch_v1(p_days integer, p_limit integer),
  public.rpc_get_calendar_feed_dev_v1(p_user_id uuid, p_date_from timestamp with time zone, p_date_to timestamp with time zone, p_limit integer),
  public.rpc_get_chat_inbox_v1(p_limit integer),
  public.rpc_get_chat_thread_v1(p_thread_id uuid, p_limit integer),
  public.rpc_get_event_detail_dev_v1(p_user_id uuid, p_event_id uuid),
  public.rpc_get_event_detail_v1(p_event_id uuid),
  public.rpc_get_item_detail(p_item_ref uuid),
  public.rpc_get_or_create_wishlist(),
  public.rpc_get_provenance_audit(p_limit integer),
  public.rpc_get_quickscan_draft_from_event_dev_v1(p_user_id uuid, p_event_id uuid),
  public.rpc_get_quickscan_prefill_dev_v1(p_user_id uuid, p_item_id uuid),
  public.rpc_get_quickscan_prefill_dev_v2(p_user_id uuid, p_item_id uuid),
  public.rpc_get_quickscan_prefill_v1(p_item_id uuid),
  public.rpc_get_quickscan_prefill_v2_dev_v1(p_user_id uuid, p_item_id uuid),
  public.rpc_get_quickscan_prefill_v3_dev_v1(p_user_id uuid, p_item_id uuid),
  public.rpc_get_quickscan_ui_state_dev_v1(p_user_id uuid, p_item_id uuid),
  public.rpc_get_quickscan_ui_state_dev_v2(p_user_id uuid, p_item_id uuid),
  public.rpc_get_quickscan_ui_state_v2(p_item_id uuid),
  public.rpc_get_quickscan_ui_state_v2_badges(p_item_id uuid),
  public.rpc_get_quickscan_ui_state_v2_polished(p_item_id uuid),
  public.rpc_get_quickscan_v2_dev_v1(p_user_id uuid, p_item_id uuid),
  public.rpc_get_task_status_v1(p_task_id uuid),
  public.rpc_get_user_activity_v1(p_user_id uuid, p_limit integer, p_offset integer),
  public.rpc_home_feed(p_user_id uuid, p_take integer),
  public.rpc_ingest_event_dev_v1(p_source text, p_event_type text, p_title text, p_starts_at timestamp with time zone, p_source_event_id text, p_description text, p_category text, p_canonical_key text, p_url text, p_city text, p_country text, p_venue_name text, p_latitude numeric, p_longitude numeric, p_ends_at timestamp with time zone, p_is_cancelled boolean),
  public.rpc_ingest_event_v1(p_source text, p_event_type text, p_title text, p_starts_at timestamp with time zone, p_source_event_id text, p_description text, p_category text, p_canonical_key text, p_url text, p_city text, p_country text, p_venue_name text, p_latitude numeric, p_longitude numeric, p_ends_at timestamp with time zone, p_is_cancelled boolean),
  public.rpc_ingest_events_batch_dev_v1(p_payload jsonb),
  public.rpc_ingest_events_batch_gated_dev_v1(p_user_id uuid, p_payload jsonb, p_mode text),
  public.rpc_ingest_market_hits(p_hits jsonb),
  public.rpc_item_timeseries_90d(p_item_ref uuid),
  public.rpc_join_category_chat_v1(p_category text),
  public.rpc_lens_list(p_after_item_ref uuid, p_brand text, p_set_name text, p_category text, p_search text, p_sort text, p_limit integer),
  public.rpc_lens_list_v2(p_after uuid, p_brand text, p_set_name text, p_category text, p_q text, p_sort text, p_limit integer),
  public.rpc_list_personalized_events_v1(p_user_id text, p_category_id text, p_include_past boolean),
  public.rpc_lock_item_identity_v1(p_item_id uuid),
  public.rpc_log_activity_v1(p_activity_type text, p_title text, p_description text, p_metadata jsonb, p_is_public boolean),
  public.rpc_portfolio_snapshot_all_users_v1(p_as_of_date date),
  public.rpc_portfolio_snapshot_upsert_v1(p_user_id uuid, p_as_of_date date),
  public.rpc_prune_maintenance(),
  public.rpc_quickscan_apply_extractions_dev_v1(p_user_id uuid, p_item_id uuid, p_min_conf_confirm numeric, p_min_conf_suggest numeric),
  public.rpc_quickscan_apply_extractions_v1(p_item_id uuid, p_min_conf_confirm numeric, p_min_conf_suggest numeric),
  public.rpc_quickscan_autofill_v1(p_item_id uuid),
  public.rpc_quickscan_confirm_all_suggestions_dev_v1(p_user_id uuid, p_item_id uuid),
  public.rpc_quickscan_confirm_all_suggestions_v1(p_item_id uuid),
  public.rpc_quickscan_confirm_price_dev_v1(p_user_id uuid, p_item_id uuid, p_price_eur numeric),
  public.rpc_quickscan_confirm_price_v1(p_item_id uuid, p_price_eur numeric),
  public.rpc_quickscan_confirm_suggestions_and_state_v1(p_item_id uuid),
  public.rpc_quickscan_create_draft_v1(p_category text, p_title_hint text, p_image_uri text, p_source text),
  public.rpc_quickscan_finalize_draft_to_item_v1(p_draft_id uuid, p_category text, p_canonical_key text, p_title text),
  public.rpc_quickscan_get_ui_state_v1(p_item_id uuid),
  public.rpc_quickscan_one_tap_dev_v1(p_user_id uuid, p_category text, p_canonical_key text, p_title_hint text, p_image_uri text, p_price_eur numeric, p_auto_confirm_suggestions boolean),
  public.rpc_quickscan_one_tap_v1(p_category text, p_canonical_key text, p_title_hint text, p_image_uri text, p_price_eur numeric, p_auto_confirm_suggestions boolean),
  public.rpc_quickscan_one_tap_v2(p_category text, p_canonical_key text, p_title_hint text, p_image_uri text, p_price_eur numeric, p_auto_confirm_suggestions boolean),
  public.rpc_quickscan_seed_extraction_from_title_dev_v1(p_user_id uuid, p_item_id uuid),
  public.rpc_quickscan_seed_extraction_from_title_v1(p_item_id uuid),
  public.rpc_register_push_device_v1(p_token text, p_platform text, p_device_label text, p_app_version text, p_provider text),
  public.rpc_run_daily_guidance_v1(p_user_id uuid),
  public.rpc_search_items(p_q text, p_limit integer),
  public.rpc_send_message_v1(p_thread_id uuid, p_user_id uuid, p_body text),
  public.rpc_set_presence_v1(p_status text, p_thread_id uuid, p_meta jsonb),
  public.rpc_submit_purchase_price_v1(p_item_ref text, p_price_eur numeric, p_condition_grade text),
  public.rpc_toggle_reaction_v1(p_message_id uuid, p_emoji text),
  public.rpc_top_movers_cached(p_limit integer, p_sort text),
  public.rpc_training_items_upsert_v1(p_category_slug text, p_canonical_key text, p_display_name text, p_attributes jsonb, p_anchor_price_eur numeric, p_anchor_price_date date, p_anchor_source text, p_source_url text, p_confidence_hint text, p_is_active boolean),
  public.rpc_unfollow_events_v1(p_canonical_key text, p_category text),
  public.rpc_unmark_category_item_owned_v1(p_category_item_id uuid),
  public.rpc_upsert_item_metadata_by_nk(p_nk text, p_category text, p_brand text, p_variant text, p_set_name text, p_language text, p_rarity text, p_release_year integer, p_notes text),
  public.rpc_watch_event_dev_v1(p_user_id uuid, p_event_id uuid, p_target_price_eur numeric, p_notes text),
  public.rpc_watch_event_v1(p_event_id uuid, p_target_price_eur numeric, p_notes text),
  public.rpc_watchlist_add_by_nk(p_user_id uuid, p_nk text),
  public.rpc_watchlist_add_by_ref(p_user_id uuid, p_item_ref uuid),
  public.rpc_watchlist_remove(p_user_id uuid, p_item_ref uuid),
  public.rpc_wishlist_disable_v1(p_canonical_key text),
  public.rpc_wishlist_upsert_v1(p_canonical_key text, p_category text, p_target_price_eur numeric, p_notes text, p_enabled boolean),
  public.secure_partition_rls(),
  public.sync_metadata_ai_v1(p_item_id uuid, p_attrs jsonb, p_ai_source text, p_ai_confidence numeric, p_force boolean),
  public.update_watchlist_valuation_v1(),
  public.upsert_item_metadata_by_ref(p_item_ref uuid, p_attrs jsonb),
  public.upsert_market_hits_batch(rows jsonb)
TO service_role;
