-- 2026-04-24: drop market_hits_legacy (516 MB) after repointing 24
-- dependent views/matviews to the partitioned `market_hits` parent.
-- Generated by scripts/gen_mh_repoint.py (view substitution) + manual
-- sequence detach + drop. Final advisor state: back to 10 findings
-- (same as before the drop — no new regressions).

DROP MATERIALIZED VIEW IF EXISTS public.category_daily_medians CASCADE;
CREATE MATERIALIZED VIEW public.category_daily_medians AS
 SELECT category,
    date_trunc('day'::text, observed_at) AS day_bucket,
    percentile_cont(0.5::double precision) WITHIN GROUP (ORDER BY (price::double precision)) AS med_mkt,
    count(*) AS n_obs
   FROM market_hits
  WHERE price IS NOT NULL
  GROUP BY category, (date_trunc('day'::text, observed_at));;

CREATE OR REPLACE VIEW public.category_medians_30d AS
 WITH pred AS (
         SELECT COALESCE(price_predictions.category, 'unknown'::text) AS category,
            percentile_cont(0.5::double precision) WITHIN GROUP (ORDER BY (price_predictions.q50::double precision)) AS med_pred,
            count(*) AS n_pred
           FROM price_predictions
          WHERE price_predictions.q50 IS NOT NULL AND price_predictions.created_at >= (now() - '30 days'::interval)
          GROUP BY (COALESCE(price_predictions.category, 'unknown'::text))
        ), mkt AS (
         SELECT COALESCE(market_hits.category, 'unknown'::text) AS category,
            percentile_cont(0.5::double precision) WITHIN GROUP (ORDER BY (market_hits.price::double precision)) AS med_mkt,
            count(*) AS n_mkt
           FROM market_hits
          WHERE market_hits.price IS NOT NULL AND market_hits.observed_at >= (now() - '30 days'::interval)
          GROUP BY (COALESCE(market_hits.category, 'unknown'::text))
        )
 SELECT COALESCE(p.category, m.category) AS category,
    p.med_pred,
    p.n_pred,
    m.med_mkt,
    m.n_mkt
   FROM pred p
     FULL JOIN mkt m USING (category)
  ORDER BY (COALESCE(p.category, m.category));;

CREATE OR REPLACE VIEW public.fx_coverage_diag_v1 AS
 WITH by_curr AS (
         SELECT upper(mh.currency) AS currency,
            count(*)::integer AS rows_total,
            sum(
                CASE
                    WHEN fr.rate_to_eur IS NULL THEN 1
                    ELSE 0
                END)::integer AS rows_missing_rate
           FROM market_hits mh
             LEFT JOIN fx_rates_v1 fr ON upper(fr.currency) = upper(mh.currency)
          GROUP BY (upper(mh.currency))
        )
 SELECT currency,
    rows_total,
    rows_missing_rate,
        CASE
            WHEN rows_total > 0 THEN round(rows_missing_rate::numeric / rows_total::numeric * 100::numeric, 2)
            ELSE NULL::numeric
        END AS missing_pct
   FROM by_curr b
  ORDER BY rows_total DESC;;

CREATE OR REPLACE VIEW public.item_coverage_snapshot_v1 AS
 WITH base AS (
         SELECT market_hits.category,
            market_hits.item_ref,
            market_hits.observed_at
           FROM market_hits
          WHERE market_hits.item_ref IS NOT NULL
        ), overall AS (
         SELECT base.category,
            count(DISTINCT base.item_ref)::integer AS distinct_items
           FROM base
          GROUP BY base.category
        ), recent AS (
         SELECT base.category,
            count(DISTINCT base.item_ref)::integer AS distinct_items_30d
           FROM base
          WHERE base.observed_at IS NOT NULL AND base.observed_at > (now() - '30 days'::interval)
          GROUP BY base.category
        )
 SELECT COALESCE(o.category, r.category) AS category,
    COALESCE(o.distinct_items, 0) AS distinct_items,
    COALESCE(r.distinct_items_30d, 0) AS distinct_items_30d
   FROM overall o
     FULL JOIN recent r USING (category);;

CREATE OR REPLACE VIEW public.market_data_coverage AS
 SELECT ( SELECT count(*) AS count
           FROM price_predictions
          WHERE price_predictions.created_at >= (now() - '30 days'::interval)) AS preds_30d,
    ( SELECT count(*) AS count
           FROM market_hits
          WHERE market_hits.observed_at >= (now() - '30 days'::interval)) AS market_30d,
    ( SELECT count(*) AS count
           FROM market_hits
          WHERE market_hits.item_ref IS NOT NULL) AS market_with_item_ref,
    ( SELECT count(*) AS count
           FROM market_hits
          WHERE market_hits.item_ref IS NULL) AS market_missing_item_ref;;

CREATE OR REPLACE VIEW public.market_hits_enriched_v1 AS
 WITH hits AS (
         SELECT h_1.id,
            h_1.user_id,
            h_1.title,
            h_1.url,
            h_1.price,
            h_1.currency,
            h_1.image_url,
            h_1.marketplace,
            h_1.seen_at,
            h_1.item_ref,
            h_1.category,
            h_1.source,
            h_1.observed_at,
            h_1.condition_grade,
            h_1.tx_id,
            h_1.seller_rating,
            h_1.url_hash,
                CASE
                    WHEN h_1.item_ref ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'::text THEN h_1.item_ref::uuid
                    ELSE NULL::uuid
                END AS item_ref_uuid
           FROM market_hits h_1
        )
 SELECT h.id,
    h.user_id,
    h.title,
    h.url,
    h.price,
    h.currency,
    h.image_url,
    h.marketplace,
    h.seen_at,
    h.item_ref,
    h.category,
    h.source,
    h.observed_at,
    h.condition_grade,
    h.tx_id,
    h.seller_rating,
    h.url_hash,
    h.item_ref_uuid,
    m.category AS meta_category,
    m.brand AS meta_brand,
    m.variant AS meta_variant,
    m.set_name AS meta_set_name,
    m.condition AS meta_condition,
    m.language AS meta_language,
    m.release_year AS meta_release_year,
    m.human_override AS meta_human_override,
    m.ai_source AS meta_ai_source,
    m.ai_confidence AS meta_ai_confidence
   FROM hits h
     LEFT JOIN item_metadata m ON m.item_ref = h.item_ref_uuid;;

DROP MATERIALIZED VIEW IF EXISTS public.mv_item_best_comp CASCADE;
CREATE MATERIALIZED VIEW public.mv_item_best_comp AS
 SELECT ti.id AS item_id,
    mh.id AS hit_id,
    mh.created_at AS seen_at
   FROM training_items ti
     JOIN LATERAL ( SELECT market_hits.id,
            ti.created_at,
            market_hits.category
           FROM market_hits
          WHERE market_hits.category = ti.category
          ORDER BY ti.created_at DESC
         LIMIT 1) mh ON true;;

CREATE OR REPLACE VIEW public.price_samples_enriched_item_v1 AS
 SELECT mh.category,
    mh.item_ref,
    mh.price,
    mh.currency,
    mh.source,
    sw.base_weight,
        CASE
            WHEN sw.decay_half_life_days IS NULL OR mh.observed_at IS NULL THEN 1.0
            ELSE power(0.5, GREATEST(0::numeric, EXTRACT(epoch FROM now() - mh.observed_at) / 86400.0) / sw.decay_half_life_days::numeric)
        END AS time_decay,
    1.0 AS volume_lift
   FROM market_hits mh
     LEFT JOIN source_weights sw ON sw.source = mh.source
  WHERE mh.item_ref IS NOT NULL;;

CREATE OR REPLACE VIEW public.price_samples_enriched_v1 AS
 SELECT mh.category,
    mh.price,
    mh.currency,
    mh.source,
    sw.base_weight,
    power(0.5, GREATEST(0::numeric, EXTRACT(epoch FROM now() - mh.observed_at) / 86400.0) / COALESCE(sw.decay_half_life_days, 30)::numeric) AS time_decay,
    1.0 AS volume_lift
   FROM market_hits mh
     LEFT JOIN source_weights sw ON sw.source = mh.source;;

CREATE OR REPLACE VIEW public.price_samples_fx_input_v1 AS
 SELECT mh.category,
    mh.price AS price_raw,
    mh.currency,
    mh.source,
    fr.rate_to_eur,
    mh.price * COALESCE(fr.rate_to_eur, 1.0) AS price_eur
   FROM market_hits mh
     LEFT JOIN fx_rates_v1 fr ON upper(fr.currency) = upper(mh.currency);;

CREATE OR REPLACE VIEW public.v_cap_config_effective_v1 AS
 WITH cats AS (
         SELECT DISTINCT items.category
           FROM items
          WHERE items.category IS NOT NULL
        UNION
         SELECT DISTINCT prediction_cap_overrides.category
           FROM prediction_cap_overrides
          WHERE prediction_cap_overrides.category IS NOT NULL
        UNION
         SELECT DISTINCT market_hits.category
           FROM market_hits
          WHERE market_hits.category IS NOT NULL
        )
 SELECT c.category,
    COALESCE(o.cap_fraction, 0.25) AS cap_fraction,
        CASE
            WHEN o.cap_fraction IS NULL THEN 'default'::text
            ELSE 'override'::text
        END AS source
   FROM cats c
     LEFT JOIN prediction_cap_overrides o ON o.category = c.category;;

CREATE OR REPLACE VIEW public.v_coverage AS
 WITH hits AS (
         SELECT count(*) AS c
           FROM market_hits
        ), uuid_hits AS (
         SELECT count(*) AS c
           FROM market_hits
          WHERE market_hits.item_ref ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'::text
        ), linked AS (
         SELECT count(*) AS c
           FROM market_hits h
             JOIN item_metadata m ON m.item_ref = h.item_ref::uuid
          WHERE h.item_ref ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'::text
        )
 SELECT ( SELECT hits.c
           FROM hits) AS hits_total,
    ( SELECT uuid_hits.c
           FROM uuid_hits) AS hits_with_uuid_item_ref,
    ( SELECT linked.c
           FROM linked) AS hits_linked_to_metadata,
        CASE
            WHEN (( SELECT uuid_hits.c
               FROM uuid_hits)) = 0 THEN 0::numeric
            ELSE round((( SELECT linked.c
               FROM linked))::numeric * 100::numeric / (( SELECT uuid_hits.c
               FROM uuid_hits))::numeric, 2)
        END AS link_coverage_pct;;

CREATE OR REPLACE VIEW public.v_hits_qc_flags_v2 AS
 SELECT id,
    source AS marketplace,
    category,
    title,
    price,
    currency,
    COALESCE(observed_at, seen_at) AS ts,
    price IS NULL OR price <= 0::numeric AS price_bad,
    url IS NULL OR length(url) < 10 AS url_bad,
    currency IS NULL OR length(currency) <> 3 AS ccy_bad
   FROM market_hits
  WHERE price IS NULL OR price <= 0::numeric OR url IS NULL OR length(url) < 10 OR currency IS NULL OR length(currency) <> 3;;

CREATE OR REPLACE VIEW public.v_hits_unified AS
 SELECT id,
    category,
    title,
    url,
    image_url,
    price,
    COALESCE(currency, 'EUR'::text) AS currency,
    COALESCE(observed_at, seen_at) AS ts,
    source AS marketplace,
    condition_grade,
    seller_rating,
    user_id,
    tx_id,
    item_ref,
    COALESCE(url_hash, md5((((COALESCE(url, ''::text) || '|'::text) || COALESCE(tx_id, ''::text)) || '|'::text) || COALESCE(item_ref, ''::text))) AS url_hash
   FROM market_hits mh;;

CREATE OR REPLACE VIEW public.v_item_best_comp_full AS
 SELECT ti.id AS item_id,
    ti.category AS item_category,
    mv.hit_id,
    mh.id,
    mh.user_id,
    mh.title,
    mh.url,
    mh.price,
    mh.currency,
    mh.image_url,
    mh.marketplace,
    mh.seen_at,
    mh.item_ref,
    mh.category,
    mh.source,
    mh.observed_at,
    mh.condition_grade,
    mh.tx_id,
    mh.seller_rating,
    mh.url_hash
   FROM training_items ti
     JOIN mv_item_best_comp_canon mv ON mv.item_id = ti.id
     JOIN market_hits mh ON mh.id = mv.hit_id;;

CREATE OR REPLACE VIEW public.v_item_comp_stats_30d_v1 AS
 WITH mh AS (
         SELECT norm_item_ref_v1(m.item_ref) AS item_key,
            m.marketplace,
            COALESCE(m.observed_at, m.seen_at) AS ts
           FROM market_hits m
          WHERE norm_item_ref_v1(m.item_ref) IS NOT NULL
        ), filtered AS (
         SELECT mh.item_key,
            mh.marketplace,
            mh.ts
           FROM mh
          WHERE mh.ts >= (now() - '30 days'::interval)
        )
 SELECT item_key,
    count(*)::integer AS comps_30d,
    jsonb_agg(DISTINCT marketplace) AS marketplaces_30d
   FROM filtered
  GROUP BY item_key;;

CREATE OR REPLACE VIEW public.v_item_market_coverage_30d_v1 AS
 SELECT t.user_id,
    t.item_id,
    count(mh.id)::integer AS hits_30d,
    count(DISTINCT mh.marketplace)::integer AS marketplaces_30d
   FROM v_item_ingest_targets_v1 t
     LEFT JOIN market_hits mh ON norm_valuation_key_v1(mh.item_ref) = norm_valuation_key_v1(t.valuation_key) AND COALESCE(mh.observed_at, mh.seen_at) >= (now() - '30 days'::interval)
  GROUP BY t.user_id, t.item_id;;

CREATE OR REPLACE VIEW public.v_item_price_daily_90d AS
 WITH base AS (
         SELECT h.item_ref::uuid AS item_ref_uuid,
            date_trunc('day'::text, COALESCE(h.observed_at, h.seen_at))::date AS d,
            h.price AS price_num
           FROM market_hits h
          WHERE h.item_ref ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'::text AND COALESCE(h.observed_at, h.seen_at) >= (now() - '90 days'::interval) AND h.price IS NOT NULL
        )
 SELECT item_ref_uuid,
    d,
    percentile_cont(0.5::double precision) WITHIN GROUP (ORDER BY (price_num::double precision))::numeric AS median_price
   FROM base
  GROUP BY item_ref_uuid, d;;

CREATE OR REPLACE VIEW public.v_market_hit_images_todo AS
 WITH mh AS (
         SELECT h.image_url,
            md5(COALESCE(h.image_url, ''::text)) AS url_sig,
                CASE
                    WHEN h.item_ref ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'::text THEN h.item_ref::uuid
                    ELSE NULL::uuid
                END AS item_ref
           FROM market_hits h
          WHERE h.image_url IS NOT NULL AND TRIM(BOTH FROM h.image_url) <> ''::text
        )
 SELECT DISTINCT ON (url_sig) url_sig,
    image_url,
    item_ref
   FROM mh;;

CREATE OR REPLACE VIEW public.v_market_hits_canon AS
 SELECT id,
    category,
    COALESCE(( SELECT m.canonical_category
           FROM category_map m
          WHERE m.raw_category_lower = lower(mh.category)), lower(category)) AS canonical_category
   FROM market_hits mh
  WHERE category IS NOT NULL AND TRIM(BOTH FROM category) <> ''::text;;

CREATE OR REPLACE VIEW public.v_market_hits_pending_enrich_v1 AS
 SELECT id AS hit_id,
    user_id,
    item_ref,
    category,
    title,
    url,
    price,
    currency,
    image_url,
    marketplace,
    observed_at,
    source
   FROM market_hits h
  WHERE processed = false AND url IS NOT NULL AND url <> ''::text AND item_ref IS NOT NULL AND item_ref <> ''::text AND user_id IS NOT NULL AND price IS NOT NULL AND currency IS NOT NULL AND currency <> ''::text;;

CREATE OR REPLACE VIEW public.v_provenance_audit AS
 WITH mh AS (
         SELECT mh_1.item_ref,
            count(*) AS hits_total,
            count(*) FILTER (WHERE mh_1.price IS NOT NULL) AS hits_with_price,
            min(COALESCE(mh_1.observed_at, mh_1.seen_at)) AS first_seen,
            max(COALESCE(mh_1.observed_at, mh_1.seen_at)) AS last_seen
           FROM market_hits mh_1
          WHERE mh_1.item_ref ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'::text
          GROUP BY mh_1.item_ref
        )
 SELECT m.item_ref,
    m.category,
    m.brand,
    m.variant,
    m.set_name,
    m.rarity,
    m.language,
    mh.hits_total,
    mh.hits_with_price,
    mh.first_seen,
    mh.last_seen,
    concat_ws(' '::text,
        CASE
            WHEN m.brand IS NULL OR m.brand = ''::text THEN 'missing_brand'::text
            ELSE NULL::text
        END,
        CASE
            WHEN m.variant IS NULL OR m.variant = ''::text THEN 'missing_variant'::text
            ELSE NULL::text
        END,
        CASE
            WHEN m.set_name IS NULL OR m.set_name = ''::text THEN 'missing_set'::text
            ELSE NULL::text
        END,
        CASE
            WHEN mh.hits_total IS NULL THEN 'no_hits'::text
            ELSE NULL::text
        END) AS issues
   FROM item_metadata m
     LEFT JOIN mh ON mh.item_ref::uuid = m.item_ref
  ORDER BY (concat_ws(' '::text,
        CASE
            WHEN m.brand IS NULL OR m.brand = ''::text THEN 'missing_brand'::text
            ELSE NULL::text
        END,
        CASE
            WHEN m.variant IS NULL OR m.variant = ''::text THEN 'missing_variant'::text
            ELSE NULL::text
        END,
        CASE
            WHEN m.set_name IS NULL OR m.set_name = ''::text THEN 'missing_set'::text
            ELSE NULL::text
        END,
        CASE
            WHEN mh.hits_total IS NULL THEN 'no_hits'::text
            ELSE NULL::text
        END)) DESC NULLS LAST, mh.last_seen DESC NULLS LAST;;

CREATE OR REPLACE VIEW public.v_valuation_comp_stats_30d_v1 AS
 WITH mh AS (
         SELECT norm_valuation_key_v1(m.item_ref) AS valuation_key,
            m.marketplace,
            COALESCE(m.observed_at, m.seen_at) AS ts
           FROM market_hits m
          WHERE norm_valuation_key_v1(m.item_ref) IS NOT NULL
        ), filtered AS (
         SELECT mh.valuation_key,
            mh.marketplace,
            mh.ts
           FROM mh
          WHERE mh.ts >= (now() - '30 days'::interval)
        )
 SELECT valuation_key,
    count(*)::integer AS comps_30d,
    jsonb_agg(DISTINCT marketplace) AS marketplaces_30d
   FROM filtered
  GROUP BY valuation_key;;


-- Detach shared sequence (partitioned children still use market_hits_id_seq
-- for their id default), then drop the legacy table.
ALTER SEQUENCE public.market_hits_id_seq OWNED BY NONE;
DROP TABLE public.market_hits_legacy;

-- Re-flip any recreated matviews/views to SECURITY INVOKER (CREATE defaults
-- to DEFINER) and re-revoke matview grants from anon/authenticated.
DO $$ DECLARE v text; BEGIN
  FOR v IN SELECT viewname FROM pg_views vv WHERE vv.schemaname='public'
    AND EXISTS (SELECT 1 FROM pg_class c2 JOIN pg_namespace n ON c2.relnamespace=n.oid
                WHERE n.nspname=vv.schemaname AND c2.relname=vv.viewname
                AND (c2.reloptions IS NULL OR NOT 'security_invoker=true' = ANY(c2.reloptions)))
  LOOP EXECUTE format('ALTER VIEW public.%I SET (security_invoker = true)', v); END LOOP;
END $$;

DO $$ DECLARE m text; BEGIN
  FOR m IN SELECT matviewname FROM pg_matviews WHERE schemaname='public'
  LOOP EXECUTE format('REVOKE ALL ON public.%I FROM anon, authenticated', m); END LOOP;
END $$;
