-- Evidence-Native Schema Expansion
-- Implements: item attributes, provenance tracking, evidence bundles,
--             alert history, and feedback-to-retraining metadata.
-- Created: 2026-02-10

BEGIN;

-- ============================================================================
-- 1. Item attributes JSONB column
--    Stores category-specific attributes (condition, grade, set, edition, etc.)
-- ============================================================================
ALTER TABLE public.items
  ADD COLUMN IF NOT EXISTS attributes_json JSONB DEFAULT '{}'::JSONB,
  ADD COLUMN IF NOT EXISTS taxonomy_version TEXT DEFAULT 'v1.0',
  ADD COLUMN IF NOT EXISTS subtype_id TEXT,
  ADD COLUMN IF NOT EXISTS collections TEXT[] DEFAULT '{}';

COMMENT ON COLUMN public.items.attributes_json IS
'Category-specific attributes: condition, grade, edition, set, rarity, etc.';
COMMENT ON COLUMN public.items.taxonomy_version IS
'Version of taxonomy used when this item was classified.';

-- ============================================================================
-- 2. Item provenance events (replace in-memory dict)
--    Tracks ownership history: added, transferred, sold, purchased, verified
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.item_provenance_events (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    item_id TEXT NOT NULL,
    user_id TEXT NOT NULL,
    event_type TEXT NOT NULL CHECK (event_type IN (
      'added', 'transferred_in', 'transferred_out',
      'sale', 'purchase', 'graded', 'verified', 'updated'
    )),
    note TEXT,
    source TEXT CHECK (source IS NULL OR source IN ('manual', 'receipt', 'marketplace', 'ocr', 'barcode', 'import', 'admin')),
    metadata JSONB DEFAULT '{}'::JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_provenance_item_id ON public.item_provenance_events (item_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_provenance_user_id ON public.item_provenance_events (user_id);

ALTER TABLE public.item_provenance_events ENABLE ROW LEVEL SECURITY;

CREATE POLICY "provenance_select_own" ON public.item_provenance_events
  FOR SELECT TO authenticated USING (auth.uid()::text = user_id);

CREATE POLICY "provenance_insert_own" ON public.item_provenance_events
  FOR INSERT TO authenticated WITH CHECK (auth.uid()::text = user_id);

CREATE POLICY "service_role_provenance" ON public.item_provenance_events
  FOR ALL TO service_role USING (true) WITH CHECK (true);

-- ============================================================================
-- 3. Evidence bundles on price_predictions
--    Link predictions to the actual market_hits that informed them
-- ============================================================================
ALTER TABLE public.price_predictions
  ADD COLUMN IF NOT EXISTS evidence_hit_ids TEXT[] DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS taxonomy_version TEXT DEFAULT 'v1.0',
  ADD COLUMN IF NOT EXISTS explanation TEXT,
  ADD COLUMN IF NOT EXISTS evidence_summary JSONB DEFAULT '{}'::JSONB;

COMMENT ON COLUMN public.price_predictions.evidence_hit_ids IS
'Array of market_hits IDs that were used as comparables for this prediction.';
COMMENT ON COLUMN public.price_predictions.evidence_summary IS
'Aggregated evidence: {sources: [{source, count, avg_price, date_range}], total_comps}';
COMMENT ON COLUMN public.price_predictions.explanation IS
'Human-readable "Why this price?" text generated by explainer.';

-- ============================================================================
-- 4. Alert trigger history
--    Persists triggered alerts (not just thresholds) for the Monitored pillar
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.alert_trigger_history (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    alert_id UUID REFERENCES public.user_price_alerts(id),
    user_id UUID NOT NULL,
    item_id TEXT,
    trigger_type TEXT NOT NULL,
    trigger_value JSONB NOT NULL,   -- {current_price, previous_price, threshold, pct_change, z_score}
    message TEXT NOT NULL,
    read BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_alert_history_user ON public.alert_trigger_history (user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_alert_history_unread ON public.alert_trigger_history (user_id, read) WHERE read = FALSE;
CREATE INDEX IF NOT EXISTS idx_alert_history_alert ON public.alert_trigger_history (alert_id);

ALTER TABLE public.alert_trigger_history ENABLE ROW LEVEL SECURITY;

CREATE POLICY "alert_history_select_own" ON public.alert_trigger_history
  FOR SELECT TO authenticated USING (auth.uid() = user_id);

CREATE POLICY "alert_history_update_own" ON public.alert_trigger_history
  FOR UPDATE TO authenticated USING (auth.uid() = user_id);

CREATE POLICY "service_role_alert_history" ON public.alert_trigger_history
  FOR ALL TO service_role USING (true) WITH CHECK (true);

-- ============================================================================
-- 5. Price history for anomaly detection
--    Tracks rolling price snapshots per item for z-score computation
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.price_history (
    id BIGSERIAL PRIMARY KEY,
    item_ref TEXT NOT NULL,
    price_q50 NUMERIC NOT NULL,
    price_q10 NUMERIC,
    price_q90 NUMERIC,
    source TEXT DEFAULT 'valuation_worker',
    snapshot_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_price_history_item ON public.price_history (item_ref, snapshot_at DESC);

ALTER TABLE public.price_history ENABLE ROW LEVEL SECURITY;

CREATE POLICY "service_role_price_history" ON public.price_history
  FOR ALL TO service_role USING (true) WITH CHECK (true);

CREATE POLICY "users_read_price_history" ON public.price_history
  FOR SELECT TO authenticated USING (true);

-- ============================================================================
-- 6. Taxonomy correction log
--    Tracks user category corrections for auto-taxonomy improvement
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.taxonomy_corrections (
    id BIGSERIAL PRIMARY KEY,
    user_id TEXT NOT NULL,
    item_id TEXT,
    original_category TEXT NOT NULL,
    corrected_category TEXT NOT NULL,
    original_subtype TEXT,
    corrected_subtype TEXT,
    taxonomy_version TEXT NOT NULL DEFAULT 'v1.0',
    source TEXT DEFAULT 'app',  -- 'app', 'admin', 'feedback'
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_taxonomy_corrections_cats ON public.taxonomy_corrections (original_category, corrected_category);
CREATE INDEX IF NOT EXISTS idx_taxonomy_corrections_version ON public.taxonomy_corrections (taxonomy_version);

ALTER TABLE public.taxonomy_corrections ENABLE ROW LEVEL SECURITY;

CREATE POLICY "taxonomy_corrections_insert" ON public.taxonomy_corrections
  FOR INSERT TO authenticated WITH CHECK (auth.uid()::text = user_id);

CREATE POLICY "service_role_taxonomy_corrections" ON public.taxonomy_corrections
  FOR ALL TO service_role USING (true) WITH CHECK (true);

-- ============================================================================
-- 7. Feedback retraining metadata
--    Tracks when feedback was incorporated into model training
-- ============================================================================
ALTER TABLE public.user_feedback_events_v1
  ADD COLUMN IF NOT EXISTS incorporated_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS incorporated_run_id TEXT;

COMMENT ON COLUMN public.user_feedback_events_v1.incorporated_at IS
'When this feedback was used in model retraining (NULL = not yet used).';

-- ============================================================================
-- 8. Set completion tracking (for "missing item" suggestions)
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.set_registry (
    id TEXT PRIMARY KEY,                 -- e.g., 'pokemon:base_set'
    category_id TEXT NOT NULL,
    set_name TEXT NOT NULL,
    total_items INTEGER NOT NULL,
    items_json JSONB NOT NULL,           -- [{key, name, number, rarity}]
    source TEXT DEFAULT 'catalog',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_set_registry_category ON public.set_registry (category_id);

ALTER TABLE public.set_registry ENABLE ROW LEVEL SECURITY;

CREATE POLICY "set_registry_read" ON public.set_registry
  FOR SELECT TO authenticated USING (true);

CREATE POLICY "service_role_set_registry" ON public.set_registry
  FOR ALL TO service_role USING (true) WITH CHECK (true);

-- ============================================================================
-- 9. View: v_item_with_evidence
--    Joins items with latest prediction and evidence for the UI
-- ============================================================================
CREATE OR REPLACE VIEW public.v_item_with_evidence AS
SELECT
    i.id,
    i.user_id,
    i.name,
    i.category,
    i.subtype_id,
    i.taxonomy_version,
    i.collections,
    i.attributes_json,
    pp.q10,
    pp.q50,
    pp.q90,
    pp.confidence,
    pp.explanation,
    pp.evidence_summary,
    pp.evidence_hit_ids,
    pp.model_version,
    pp.created_at AS prediction_at
FROM public.items i
LEFT JOIN LATERAL (
    SELECT *
    FROM public.price_predictions pp2
    WHERE pp2.nk = i.id::text
    ORDER BY pp2.created_at DESC
    LIMIT 1
) pp ON true;

COMMIT;
